# Libraries

In [ ]:
pip install Faker

In [ ]:
pip install numpy

In [ ]:
pip install DateTime

In [ ]:
pip install pandas

In [ ]:
pip install pycountry_convert

In [1]:
import random
from random import randint
import datetime
from faker import Faker
fake = Faker()
import pandas as pd
import numpy as np
import pycountry_convert as pc
from datetime import timedelta

# List of Countries, States

In [2]:
countries_list = ['Afghanistan','Albania','Algeria','Andorra','Angola',
                  'Antigua & Deps','Argentina','Armenia','Australia',
                  'Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh',
                  'Barbados','Belarus','Belgium','Belize','Benin','Bhutan',
                  'Bolivia','Bosnia Herzegovina','Botswana','Brazil',
                  'Brunei','Bulgaria','Burkina','Burundi','Cambodia',
                  'Cameroon','Canada','Cape Verde','Central African Rep',
                  'Chad','Chile','China','Colombia','Comoros','Congo',
                  'Congo {Democratic Rep}','Costa Rica','Croatia','Cuba',
                  'Cyprus','Czech Republic','Denmark','Djibouti',
                  'Dominica','Dominican Republic','East Timor','Ecuador',
                  'Egypt','El Salvador','Equatorial Guinea','Eritrea',
                  'Estonia','Ethiopia','Fiji','Finland','France','Gabon',
                  'Gambia','Georgia','Germany','Ghana','Greece','Grenada',
                  'Guatemala','Guinea','Guinea-Bissau','Guyana','Haiti',
                  'Honduras','Hungary','Iceland','India','Indonesia','Iran',
                  'Iraq','Ireland {Republic}','Israel','Italy','Ivory Coast',
                  'Jamaica','Japan','Jordan','Kazakhstan','Kenya','Kiribati',
                  'Korea North','Korea South','Kuwait',
                  'Kyrgyzstan','Laos','Latvia','Lebanon','Lesotho',
                  'Liberia','Libya','Liechtenstein','Lithuania',
                  'Luxembourg','Macedonia','Madagascar','Malawi',
                  'Malaysia','Maldives','Mali','Malta','Marshall Islands',
                  'Mauritania','Mauritius','Mexico','Moldova',
                  'Monaco','Mongolia','Montenegro','Morocco','Mozambique',
                  'Myanmar{Burma}','Namibia','Nauru','Nepal','Netherlands',
                  'New Zealand','Nicaragua','Niger','Nigeria','Norway',
                  'Oman','Pakistan','Palau','Panama','Papua New Guinea',
                  'Paraguay','Peru','Philippines','Poland','Portugal',
                  'Qatar','Romania','Russian Federation','Rwanda',
                  'St Kitts & Nevis','St Lucia',
                  'Saint Vincent & the Grenadines','Samoa',
                  'San Marino','Sao Tome & Principe','Saudi Arabia',
                  'Senegal','Serbia','Seychelles','Sierra Leone',
                  'Singapore','Slovakia','Slovenia','Solomon Islands',
                  'Somalia','South Africa','South Sudan','Spain',
                  'Sri Lanka','Sudan','Suriname','Swaziland','Sweden',
                  'Switzerland','Syria','Taiwan','Tajikistan','Tanzania',
                  'Thailand','Togo','Tonga','Trinidad & Tobago','Tunisia',
                  'Turkey','Turkmenistan','Tuvalu','Uganda','Ukraine',
                  'United Arab Emirates','United Kingdom',
                  'United States','Uruguay','Uzbekistan','Vanuatu',
                  'Vatican City','Venezuela','Vietnam','Yemen',
                  'Zambia','Zimbabwe']

In [3]:
countries_list

['Afghanistan',
 'Albania',
 'Algeria',
 'Andorra',
 'Angola',
 'Antigua & Deps',
 'Argentina',
 'Armenia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bhutan',
 'Bolivia',
 'Bosnia Herzegovina',
 'Botswana',
 'Brazil',
 'Brunei',
 'Bulgaria',
 'Burkina',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Central African Rep',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Congo {Democratic Rep}',
 'Costa Rica',
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'East Timor',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Ethiopia',
 'Fiji',
 'Finland',
 'France',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Greece',
 'Grenada',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Honduras',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland {Republic}',
 'Israel',
 'Italy',
 'Ivory Coast',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Korea North',
 'Korea South',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Luxembourg',
 'Macedonia',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Morocco',
 'Mozambique',
 'Myanmar{Burma}',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Norway',
 'Oman',
 'Pakistan',
 'Palau',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Qatar',
 'Romania',
 'Russian Federation',
 'Rwanda',
 'St Kitts & Nevis',
 'St Lucia',
 'Saint Vincent & the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome & Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Swaziland',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Togo',
 'Tonga',
 'Trinidad & Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican City',
 'Venezuela',
 'Vietnam',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [4]:
state_US_list = ['Alabama','Alaska','Arizona','Arkansas',
                 'California','Colorado','Connecticut',
                 'Delaware','Florida','Georgia','Hawaii',
                 'Idaho','Illinois','Indiana','Iowa','Kansas',
                 'Kentucky','Louisiana','Maine',
                 'Maryland','Massachusetts','Michigan','Minnesota',
                 'Mississippi','Missouri','Montana','Nebraska',
                 'Nevada','New Hampshire','New Jersey','New Mexico',
                 'New York','North Carolina','North Dakota','Ohio',
                 'Oklahoma','Oregon','Pennsylvania','Rhode Island',
                 'South Carolina','South Dakota','Tennessee','Texas',
                 'Utah','Vermont','Virginia','Washington',
                 'West Virginia','Wisconsin','Wyoming']

In [5]:
state_US_list

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming']

In [6]:
marital_status = ['Married','Single','Divorced','Widowed','Marriage Anulled','Legally Separated']

In [ ]:
#'[]PassportNumber': fake.pystr_format(string_format='?#-###{{random_int}}{{random_letter}}', letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'),

# 1: Random Data - Red / Yellow / Green

## 1.1: Generating Independent Attributes

In [794]:
def make_people(num):
    
    #CountryOfBirthofSpouse = random.choice(countries_list)
    Faker.seed(5230)

    fake_people = [{'ApplicantID':x+1300000,
                  '[I130]PeopleNamePetitioner':fake.name(), 
                  '[I130A]PeopleNameBeneficiary':fake.name(),  
                  '[I130]DOBPetitioner':fake.date_between(start_date='-60y', end_date='-21y'),  
                  '[I130A]DOBBeneficiary':fake.date_between(start_date='-60y', end_date='-21y'),
                  '[I130]MailingStateFilingPetitioner':random.choice(state_US_list), 
                  '[I130A]CountryOfBirthBeneficiary':random.choice(countries_list),
                  '[I130A]GenderBeneficiary': np.random.choice(["M", "F"], p=[0.5447, 0.4553]),
                  '[I130]PassportExpiryBeneficiary':fake.date_between(start_date='+1y', end_date='+10y'),
                  '[I130]PreviousMaritalStatusPetitioner': np.random.choice(['Married','Single','Divorced','Widowed','Marriage Anulled','Legally Separated'],p=[0.1,0.6,0.15,0.05,0.02,0.08]),
                  '[I130]PreviousMaritalStatusBeneficiary':  np.random.choice(['Married','Single','Divorced','Widowed','Marriage Anulled','Legally Separated'],p=[0.1,0.6,0.15,0.05,0.02,0.08]),
                  '[I130]PetitionerEthnicity': np.random.choice(["Hispanic or Latino", "Not Hispanic or Latino", "Not Specified"], p=[0.3, 0.6, 0.1]),
                  '[I130]PetitionerRace':  np.random.choice(["White","Asian","Black or African Ammerican","American Indian or Alaska Native","Native Hawaiian or Other Pacific Islander"]),
                  '[I130]PetitionerCitizenStatus':np.random.choice(["US Citizen","Lawful Permanent Resident"]) , 
                  '[I864]RegularIncome': np.random.choice([random.randint(8000, 20000),random.randint(20000,40000),random.randint(40000, 60000),random.randint(60000,100000),random.randint(100000, 150000),random.randint(150000, 250000),random.randint(250000,1000000)],p=[0.15,0.25,0.30,0.2,0.06,0.03,0.01]),
                  '[I864]SupplementalIncome': np.random.choice([random.randint(0, 8000),random.randint(8000,20000),random.randint(20000, 40000),random.randint(40000,60000),random.randint(60000, 100000),random.randint(100000, 250000),random.randint(250000,1000000)],p=[0.15,0.25,0.30,0.2,0.06,0.03,0.01]),
                  '[I130]StayingTogetherStatus':np.random.choice(["Different States","Same State - Different Address","Same House"],p=[0.2,0.3,0.5]),
                  '[I130]CurrentMaritalStatus':np.random.choice(["Married", "Separated"], p=[0.75, 0.25]),
                  '[I864]FederalTaxFiled':  np.random.choice(["Yes", "No"], p=[0.85, 0.15]),
                  '[I485-130]SameEmployer':np.random.choice(["No", "Yes"], p=[0.75, 0.25]),
                  '[I130]ImmigrationProceeding':np.random.choice(["No", "Yes"], p=[0.9, 0.1]),
                  '[I485]CriminalityProvedConvicted':  np.random.choice(["No", "Yes"], p=[0.85, 0.15]),
                  '[I130]PreviousPetitionFiledPetitionerSameSpouse': np.random.choice(["No", "Yes"], p=[0.85, 0.15]),
                  '[I130]PreviousPetitionFiledDifferentSpouse': np.random.choice(["No", "Yes"], p=[0.8, 0.20]),
                  '[I130A]BeneficiaryInUS': np.random.choice(["Yes", "No"], p=[0.85, 0.15]),
                  '[I130-MarriageCertificate]SamePreparorNoterMinister': np.random.choice(["Yes", "No"], p=[0.1, 0.9])  
                   } for x in range(num)]
       
    return fake_people

In [795]:
people_df = pd.DataFrame(make_people(num=50000))
people_df.head(10)

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]StayingTogetherStatus,[I130]CurrentMaritalStatus,[I864]FederalTaxFiled,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I485]CriminalityProvedConvicted,[I130]PreviousPetitionFiledPetitionerSameSpouse,[I130]PreviousPetitionFiledDifferentSpouse,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,Same State - Different Address,Married,Yes,No,No,No,Yes,No,Yes,Yes
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,Different States,Married,Yes,Yes,No,No,No,Yes,Yes,No
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,Same House,Married,Yes,Yes,No,No,No,Yes,Yes,Yes
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,Same House,Married,Yes,No,No,No,No,Yes,Yes,No
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,Same House,Separated,Yes,No,No,No,No,No,Yes,No
5,1300005,Ashley Hicks,Randy Anderson,1963-02-17,1981-12-22,Oregon,Seychelles,M,2031-09-04,Single,...,Same House,Separated,Yes,No,No,No,No,Yes,Yes,No
6,1300006,Casey Lopez,Kelly Moore,1962-10-30,1981-03-06,West Virginia,Belize,F,2024-04-20,Single,...,Same State - Different Address,Separated,No,No,No,No,Yes,No,Yes,No
7,1300007,Jason Smith,William Wilson,1985-06-23,1965-08-08,Oregon,Uruguay,M,2026-08-14,Divorced,...,Same State - Different Address,Married,Yes,Yes,No,Yes,Yes,No,No,No
8,1300008,Mario Hernandez,Jessica Smith,1965-08-20,1967-03-04,Georgia,Nepal,F,2023-09-27,Divorced,...,Different States,Married,Yes,Yes,No,Yes,No,No,Yes,No
9,1300009,Ryan Daniel,Tammy Santos,1990-07-17,1968-02-22,North Dakota,Bosnia Herzegovina,M,2023-09-18,Single,...,Same House,Married,No,No,No,No,No,No,Yes,No

## 1.2: Generating Dependent Attributes

In [796]:
people_df['[I130]GenderPetitioner'] = people_df['[I130A]GenderBeneficiary'].apply(lambda x: 'M' if x == 'F' else 'F')

In [797]:
people_df['[I130]PreviousLegallySeperatedCountryPetitioner'] = people_df['[I130]PreviousMaritalStatusPetitioner'].apply(lambda x: np.random.choice(countries_list,p=[0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.807,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001]) if x == 'Legally Separated' else 'NA')

In [798]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I864]FederalTaxFiled,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I485]CriminalityProvedConvicted,[I130]PreviousPetitionFiledPetitionerSameSpouse,[I130]PreviousPetitionFiledDifferentSpouse,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[I130]GenderPetitioner,[I130]PreviousLegallySeperatedCountryPetitioner
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,Yes,No,No,No,Yes,No,Yes,Yes,F,NA
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,Yes,Yes,No,No,No,Yes,Yes,No,M,NA
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,Yes,Yes,No,No,No,Yes,Yes,Yes,M,NA
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,Yes,No,No,No,No,Yes,Yes,No,M,NA
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,Yes,No,No,No,No,No,Yes,No,F,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,Yes,No,No,No,No,No,Yes,No,F,NA
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,Yes,No,No,No,No,No,Yes,No,F,NA
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,Yes,No,No,No,No,No,Yes,No,F,NA
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,Yes,No,Yes,No,No,No,Yes,No,M,NA
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,Yes,No,No,No,No,No,Yes,No,F,NA

In [799]:
people_df['[CALCULATED]AgeGapDays'] = pd.Series.abs(people_df['[I130]DOBPetitioner']-people_df['[I130A]DOBBeneficiary'])

In [800]:
def from_dob_to_age(born):
    today = datetime.date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

In [801]:
people_df['[CALCULATED]AgePetitioner'] =  people_df['[I130]DOBPetitioner'].apply(lambda x: from_dob_to_age(x))

In [802]:
people_df['[CALCULATED]AgeBeneficiary'] =  people_df['[I130A]DOBBeneficiary'].apply(lambda x: from_dob_to_age(x))

In [803]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I485]CriminalityProvedConvicted,[I130]PreviousPetitionFiledPetitionerSameSpouse,[I130]PreviousPetitionFiledDifferentSpouse,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[I130]GenderPetitioner,[I130]PreviousLegallySeperatedCountryPetitioner,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,No,Yes,No,Yes,Yes,F,NA,9088 days,33,58
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,No,No,Yes,Yes,No,M,NA,58 days,50,50
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,No,No,Yes,Yes,Yes,M,NA,6197 days,34,51
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,No,No,Yes,Yes,No,M,NA,5867 days,23,39
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,No,No,No,Yes,No,F,NA,7299 days,39,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,No,No,No,Yes,No,F,NA,7917 days,47,25
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,No,No,No,Yes,No,F,NA,3779 days,25,36
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,No,No,No,Yes,No,F,NA,7238 days,53,33
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,No,No,No,Yes,No,M,NA,2442 days,32,26
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,No,No,No,Yes,No,F,NA,5224 days,52,38

In [804]:
people_df['[CALCULATED]AgeGapYears'] = pd.Series.abs(people_df['[CALCULATED]AgePetitioner']-people_df['[CALCULATED]AgeBeneficiary'])

In [805]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]PreviousPetitionFiledPetitionerSameSpouse,[I130]PreviousPetitionFiledDifferentSpouse,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[I130]GenderPetitioner,[I130]PreviousLegallySeperatedCountryPetitioner,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,Yes,No,Yes,Yes,F,NA,9088 days,33,58,25
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,No,Yes,Yes,No,M,NA,58 days,50,50,0
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,No,Yes,Yes,Yes,M,NA,6197 days,34,51,17
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,No,Yes,Yes,No,M,NA,5867 days,23,39,16
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,No,No,Yes,No,F,NA,7299 days,39,59,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,No,No,Yes,No,F,NA,7917 days,47,25,22
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,No,No,Yes,No,F,NA,3779 days,25,36,11
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,No,No,Yes,No,F,NA,7238 days,53,33,20
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,No,No,Yes,No,M,NA,2442 days,32,26,6
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,No,No,Yes,No,F,NA,5224 days,52,38,14

In [621]:
def number_Of_Marriages(y,x):
    if y == 'Single' or y == 'Marriage Anulled':
        nom = 0
    else:
        if int(x) <= 25 and int(x) >=18:
            nom = np.random.choice([random.randint(1,2)])
        elif int(x) > 25 and int(x)<=35:
            nom = np.random.choice([random.randint(1,3)])
        elif int(x) > 35 and int(x)<=45:
            nom = np.random.choice([random.randint(1,4)])
        elif int(x) > 45 and int(x)<=55:
            nom = np.random.choice([random.randint(1,5)])
        elif int(x) > 55:
            nom = np.random.choice([random.randint(1,6)])
    return nom

In [806]:
people_df["[I130]NumberOfMarriagesPetitioner"] = people_df.apply(lambda x : number_Of_Marriages(x["[I130]PreviousMaritalStatusPetitioner"], x["[CALCULATED]AgePetitioner"]), axis=1)

In [807]:
people_df["[I130]NumberOfMarriagesBeneficiary"] = people_df.apply(lambda x : number_Of_Marriages(x["[I130]PreviousMaritalStatusBeneficiary"], x["[CALCULATED]AgeBeneficiary"]), axis=1)

In [808]:
people_df['[I485]CriminalityProvedConvictedType'] = people_df['[I485]CriminalityProvedConvicted'].apply(lambda x: np.random.choice(["Minor Reasons", "Major Reasons"], p=[0.7, 0.3]) if x == 'Yes' else 'NA')

In [27]:
#OBSOLETE
#def I94Date(x):
#      I94date = fake.date_between(start_date=x,end_date='-1y')
#      return I94date

In [28]:
#people_df['[I130]I94DateofEntry'] =  people_df['[I130A]DOBBeneficiary'].apply(lambda x: I94Date(x))

In [809]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130-MarriageCertificate]SamePreparorNoterMinister,[I130]GenderPetitioner,[I130]PreviousLegallySeperatedCountryPetitioner,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,Yes,F,NA,9088 days,33,58,25,0,0,NA
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,No,M,NA,58 days,50,50,0,4,0,NA
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,Yes,M,NA,6197 days,34,51,17,3,5,NA
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,No,M,NA,5867 days,23,39,16,0,1,NA
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,No,F,NA,7299 days,39,59,20,0,4,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,No,F,NA,7917 days,47,25,22,5,0,NA
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,No,F,NA,3779 days,25,36,11,0,0,NA
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,No,F,NA,7238 days,53,33,20,0,0,NA
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,No,M,NA,2442 days,32,26,6,0,2,NA
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,No,F,NA,5224 days,52,38,14,0,4,NA

In [810]:
people_df['[I130]PreviousFiledPetitionerSameSpouseRejectionCondition'] = people_df['[I130]PreviousPetitionFiledPetitionerSameSpouse'].apply(lambda x: np.random.choice(["Minor Reasons", "Moderate Reasons","Major Reasons"], p=[0.5, 0.35,0.15]) if x == 'Yes' else 'NA')

In [811]:
people_df['[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition'] = people_df['[I130]PreviousPetitionFiledDifferentSpouse'].apply(lambda x: np.random.choice(["Minor Reasons", "Moderate Reasons","Major Reasons"], p=[0.5, 0.35,0.15]) if x == 'Yes' else 'NA')

In [812]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]PreviousLegallySeperatedCountryPetitioner,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,NA,9088 days,33,58,25,0,0,NA,Minor Reasons,NA
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,NA,58 days,50,50,0,4,0,NA,NA,Minor Reasons
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,NA,6197 days,34,51,17,3,5,NA,NA,Major Reasons
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,NA,5867 days,23,39,16,0,1,NA,NA,Moderate Reasons
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,NA,7299 days,39,59,20,0,4,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,NA,7917 days,47,25,22,5,0,NA,NA,NA
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,NA,3779 days,25,36,11,0,0,NA,NA,NA
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,NA,7238 days,53,33,20,0,0,NA,NA,NA
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,NA,2442 days,32,26,6,0,2,NA,NA,NA
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,NA,5224 days,52,38,14,0,4,NA,NA,NA

In [33]:
#def betweenDateMarriage(x):
#    dateFor18More = datetime.date(2019,9,20)
#    enddateSet = datetime.date(2021,7,20)
#    if x> dateFor18More:
#        return fake.date_between(start_date=x, end_date=enddateSet)  
#    else:
#        return fake.date_between(start_date=dateFor18More, end_date=enddateSet)

In [34]:
#people_df['[I130]DateOfMarriage'] =  people_df['[I130]I94DateofEntry'].apply(lambda x: betweenDateMarriage(x))

In [813]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]PreviousLegallySeperatedCountryPetitioner,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,NA,9088 days,33,58,25,0,0,NA,Minor Reasons,NA
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,NA,58 days,50,50,0,4,0,NA,NA,Minor Reasons
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,NA,6197 days,34,51,17,3,5,NA,NA,Major Reasons
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,NA,5867 days,23,39,16,0,1,NA,NA,Moderate Reasons
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,NA,7299 days,39,59,20,0,4,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,NA,7917 days,47,25,22,5,0,NA,NA,NA
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,NA,3779 days,25,36,11,0,0,NA,NA,NA
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,NA,7238 days,53,33,20,0,0,NA,NA,NA
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,NA,2442 days,32,26,6,0,2,NA,NA,NA
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,NA,5224 days,52,38,14,0,4,NA,NA,NA

In [28]:
ethnicitylist = {
    'Argentina':1,
    'Bolivia':1,
    'Chile':1,
    'Colombia':1,
    'Cuba':1,
    'Dominican Republic':1,
    'Ecuador':1,
    'El Salvador':1,
    'Guatemala':1,
    'Honduras':1,
    'Mexico':1,
    'Nicaragua':1,
    'Peru':1,
    'Spain':1,
    'Venezuela':1,
}

In [29]:
def find_ethnicity(x):
    if x in ethnicitylist:
        y = ethnicitylist[x]
    else:
        y = 0
    
    if y==1:
        eth = "Hispanic or Latino"
    else:
        eth = "Not Hispanic or Latino"
    return eth

In [814]:
people_df['[I130A]BeneficiaryEthnicity'] =  people_df['[I130A]CountryOfBirthBeneficiary'].apply(lambda x: find_ethnicity(x))

In [815]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[I130A]BeneficiaryEthnicity
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,9088 days,33,58,25,0,0,NA,Minor Reasons,NA,Not Hispanic or Latino
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,58 days,50,50,0,4,0,NA,NA,Minor Reasons,Hispanic or Latino
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,6197 days,34,51,17,3,5,NA,NA,Major Reasons,Not Hispanic or Latino
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,5867 days,23,39,16,0,1,NA,NA,Moderate Reasons,Not Hispanic or Latino
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,7299 days,39,59,20,0,4,NA,NA,NA,Hispanic or Latino
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,7917 days,47,25,22,5,0,NA,NA,NA,Not Hispanic or Latino
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,3779 days,25,36,11,0,0,NA,NA,NA,Not Hispanic or Latino
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,7238 days,53,33,20,0,0,NA,NA,NA,Not Hispanic or Latino
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,2442 days,32,26,6,0,2,NA,NA,NA,Not Hispanic or Latino
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,5224 days,52,38,14,0,4,NA,NA,NA,Not Hispanic or Latino

In [32]:
def number_of_Dependents(x,y,p,q):
    if p == 0 and q == 0:
        numberOfDependents = np.random.choice([random.randint(2,3)])
    elif p > 0 or q > 0:
        if x> 45 or y > 45:
            numberOfDependents = np.random.choice([random.randint(3,7)])
        elif x<=45 and x>=30:
            if y>=30 and y<=45:
                numberOfDependents = np.random.choice([random.randint(2,5)])
            elif y<30:
                numberOfDependents = np.random.choice([random.randint(2,5)])
        elif x<30:
            if y>=30 and y<=45:
                numberOfDependents = np.random.choice([random.randint(2,5)])
            elif y<30:
                numberOfDependents = np.random.choice([random.randint(2,4)])
    return numberOfDependents

In [816]:
people_df["[I864]NumberOfDependents"] = people_df.apply(lambda x : number_of_Dependents(x["[CALCULATED]AgePetitioner"], x["[CALCULATED]AgeBeneficiary"], x["[I130]NumberOfMarriagesPetitioner"], x["[I130]NumberOfMarriagesBeneficiary"]), axis=1)

In [34]:
def federalpovertyline_calculator(x,y):
    numberOfHouseholdMembers = x+1
    baseAdditionMultiplier = numberOfHouseholdMembers - 2
    if y == "Alaska":
        baseValue = 27212
        fplvalue = baseValue + (7100*baseAdditionMultiplier)
    elif y == "Hawaii":
        baseValue = 25050
        fplvalue = baseValue + (6525*baseAdditionMultiplier)
    else:
        baseValue = 21775
        fplvalue = baseValue + (5675*baseAdditionMultiplier)
    return fplvalue

In [817]:
people_df['[CALCULATED]FederalPovertyLineValue'] = people_df.apply(lambda x : federalpovertyline_calculator(x['[I864]NumberOfDependents'], x['[I130]MailingStateFilingPetitioner']), axis=1)

In [773]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[I130A]BeneficiaryEthnicity,[I864]NumberOfDependents,[CALCULATED]FederalPovertyLineValue
0,1200000,Mckenzie Garcia,John Nichols,1991-07-27,1970-09-01,Idaho,Palau,M,2026-07-28,Single,...,51,21,0,0,NA,NA,Moderate Reasons,Not Hispanic or Latino,3,33125
1,1200001,Helen Burns,Melvin Perez,1992-12-20,1974-04-03,Texas,Tunisia,M,2023-06-29,Divorced,...,47,19,3,4,NA,NA,NA,Not Hispanic or Latino,5,44475
2,1200002,Nicole Thomas,Michelle Holt MD,1998-04-05,1993-09-05,Alabama,India,M,2026-07-05,Single,...,28,5,0,0,Major Reasons,NA,NA,Not Hispanic or Latino,2,27450
3,1200003,Mrs. Melissa Rodriguez,Brandon Edwards,1962-12-04,1979-04-08,Kentucky,Congo,M,2027-10-01,Widowed,...,42,16,2,0,NA,NA,NA,Not Hispanic or Latino,5,44475
4,1200004,Patricia Wilson,Jane Odom,1977-04-27,1977-07-21,Iowa,Maldives,F,2028-11-15,Single,...,44,0,0,1,NA,NA,Moderate Reasons,Not Hispanic or Latino,5,44475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1249995,Ricardo Barnes,Danny Smith,1970-10-13,1979-02-25,New Jersey,Cyprus,F,2029-05-18,Single,...,42,9,0,3,NA,NA,NA,Not Hispanic or Latino,4,38800
49996,1249996,Scott Torres,Sonia Hancock,1966-03-04,1965-10-31,Kentucky,Greece,M,2030-10-05,Widowed,...,55,0,5,0,NA,NA,NA,Not Hispanic or Latino,7,55825
49997,1249997,Jennifer Li,Carol Perry,1987-10-17,1997-11-02,Maine,Oman,M,2027-03-29,Single,...,23,11,0,2,NA,NA,NA,Not Hispanic or Latino,2,27450
49998,1249998,Rebecca Thomas,Heidi Montoya,1983-06-16,1991-02-08,Alabama,Guatemala,M,2024-11-14,Single,...,30,8,0,0,NA,NA,NA,Hispanic or Latino,2,27450
49999,1249999,Kathleen Jones,David Powell,1993-06-07,1993-08-15,Iowa,Kuwait,M,2024-04-23,Single,...,28,0,0,1,NA,NA,Minor Reasons,Not Hispanic or Latino,4,38800

In [818]:
people_df['[CALCULATED]TotalIncome'] = people_df['[I864]RegularIncome'] + people_df['[I864]SupplementalIncome']

In [819]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[CALCULATED]AgeGapYears,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[I130A]BeneficiaryEthnicity,[I864]NumberOfDependents,[CALCULATED]FederalPovertyLineValue,[CALCULATED]TotalIncome
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,25,0,0,NA,Minor Reasons,NA,Not Hispanic or Latino,3,33125,57639
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,0,4,0,NA,NA,Minor Reasons,Hispanic or Latino,4,38800,174829
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,17,3,5,NA,NA,Major Reasons,Not Hispanic or Latino,3,33125,35934
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,16,0,1,NA,NA,Moderate Reasons,Not Hispanic or Latino,3,33125,48019
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,20,0,4,NA,NA,NA,Hispanic or Latino,4,38800,81475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,22,5,0,NA,NA,NA,Not Hispanic or Latino,5,44475,28957
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,11,0,0,NA,NA,NA,Not Hispanic or Latino,3,33125,53486
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,20,0,0,NA,NA,NA,Not Hispanic or Latino,2,27450,91442
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,6,0,2,NA,NA,NA,Not Hispanic or Latino,3,33125,44217
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,14,0,4,NA,NA,NA,Not Hispanic or Latino,7,55825,106423

In [637]:
def marriage_date(x,y):
    enddateSet = datetime.date(2021,7,20)
    if int(x)>=45 and int(y) >= 45:
        firstdateSet = datetime.date(2014,9,20)
    elif (int(x)>=30 and int(x)<45) or (int(y)>=30 and int(y)<45):   
        firstdateSet = datetime.date(2015,9,20)
    elif (int(x)>=25 and int(x)<30) or (int(y)>=25 and int(y)<30):   
        firstdateSet = datetime.date(2017,9,20)
    elif int(x)<25 or int(y)<25:
        firstdateSet = datetime.date(2019,9,20)
    return fake.date_between(start_date=firstdateSet, end_date=enddateSet)

In [820]:
people_df['[I130]DateOfMarriage'] = people_df.apply(lambda x : marriage_date(x['[CALCULATED]AgePetitioner'], x['[CALCULATED]AgeBeneficiary']), axis=1)

In [821]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[I130A]BeneficiaryEthnicity,[I864]NumberOfDependents,[CALCULATED]FederalPovertyLineValue,[CALCULATED]TotalIncome,[I130]DateOfMarriage
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,0,0,NA,Minor Reasons,NA,Not Hispanic or Latino,3,33125,57639,2017-01-14
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,4,0,NA,NA,Minor Reasons,Hispanic or Latino,4,38800,174829,2016-06-10
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,3,5,NA,NA,Major Reasons,Not Hispanic or Latino,3,33125,35934,2018-05-01
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,0,1,NA,NA,Moderate Reasons,Not Hispanic or Latino,3,33125,48019,2021-06-14
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,0,4,NA,NA,NA,Hispanic or Latino,4,38800,81475,2021-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,5,0,NA,NA,NA,Not Hispanic or Latino,5,44475,28957,2021-06-11
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,0,0,NA,NA,NA,Not Hispanic or Latino,3,33125,53486,2016-10-29
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,0,0,NA,NA,NA,Not Hispanic or Latino,2,27450,91442,2019-12-10
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,0,2,NA,NA,NA,Not Hispanic or Latino,3,33125,44217,2017-07-17
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,0,4,NA,NA,NA,Not Hispanic or Latino,7,55825,106423,2017-12-13

In [42]:
def I94DateM(x):
    edt = x - timedelta(days=100)
    sdt = x - timedelta(days=5500)
    return fake.date_between(start_date=sdt,end_date=edt)

In [218]:
#def I94DateN(x,y):
#    edtn = x - timedelta(days=100)
#    sdtn = y + timedelta(days=5500)
#    if sdtn != '' and edtn !='':
#        return fake.date_between(start_date=sdtn,end_date=edtn)

In [822]:
people_df['[I130]I94DateofEntry'] =  people_df['[I130]DateOfMarriage'].apply(lambda x: I94DateM(x))

In [ ]:
#people_df['[I130]I94DateofEntry'] = people_df.apply(lambda x : I94DateN(x['[I130]DateOfMarriage'], x['[I130A]DOBBeneficiary']), axis=1)

In [44]:
def lastMarriageDate(x,y,z):
   
    if int(x) >= 18 and int(x) < 25 and int(z)>=1:
        sdlm= y - timedelta(days=500)
        edlm= y - timedelta(days=150)
        lmdate = fake.date_between(start_date=sdlm,end_date=edlm)
        return lmdate
    elif int(x) >= 25 and int(x)<30 and int(z)>=1:
        sdlm= y - timedelta(days=700)
        edlm= y - timedelta(days=150)
        lmdate = fake.date_between(start_date=sdlm,end_date=edlm)
        return lmdate
    elif int(x) >= 30 and int(x)<45 and int(z)>=1:
        sdlm= y - timedelta(days=900)
        edlm= y - timedelta(days=150)
        lmdate = fake.date_between(start_date=sdlm,end_date=edlm)
        return lmdate
    elif int(x) >= 45 and int(z)>=1:
        sdlm= y - timedelta(days=1000)
        edlm= y - timedelta(days=150)
        lmdate = fake.date_between(start_date=sdlm,end_date=edlm)
        return lmdate

In [823]:
people_df['[I130]LastMarriageEndDatePetitioner'] = people_df.apply(lambda x : lastMarriageDate(x['[CALCULATED]AgePetitioner'], x['[I130]DateOfMarriage'], x['[I130]NumberOfMarriagesPetitioner']), axis=1)

In [824]:
people_df['[I130]LastMarriageEndDateBeneficiary'] = people_df.apply(lambda x : lastMarriageDate(x['[CALCULATED]AgeBeneficiary'], x['[I130]DateOfMarriage'], x['[I130]NumberOfMarriagesBeneficiary']), axis=1)

In [153]:
def federalTaxNumberYears(x,y):
    if y=="Yes":
        if int(x) == 20:
            years = np.random.choice([1,2,3], p=[0.35, 0.55,0.1])
        elif int(x) > 20 and int(x) < 22:
            years = np.random.choice([1,2,3], p=[0.15, 0.5,0.35])
        elif int(x) >= 22 and int(x)< 30:
            years = np.random.choice([1,2,3,4], p=[0.05,0.1,0.25,0.6])
        elif int(x) >= 30 and int(x)< 45:
            years = np.random.choice([1,2,3,4], p=[0.025,0.05,0.175,0.75])
        elif int(x) >= 45:
            years = np.random.choice([1,2,3,4], p=[0.025,0.05,0.175,0.75])
    
    if y == "No":
        value = "NA"
    elif years >= 3:
        value = "3 or 3+ years"
    elif years >=1 and years < 3:
        value = "Under 3 years"
        
    return value

In [825]:
people_df['[I864]FederalTaxFiledYears'] = people_df.apply(lambda x : federalTaxNumberYears(x['[CALCULATED]AgePetitioner'], x['[I864]FederalTaxFiled']), axis=1)

In [826]:
people_df['[CALCULATED]LengthOfMarriage'] =  people_df['[I130]DateOfMarriage'].apply(lambda x: from_dob_to_age(x))

In [827]:
people_df['[CALCULATED]YearsSinceDateofEntry'] =  people_df['[I130]I94DateofEntry'].apply(lambda x: from_dob_to_age(x))

In [828]:
people_df['[CALCULATED]TotalYearsFromLastMarriagePetitioner'] = pd.Series.abs(people_df['[I130]DateOfMarriage'] - people_df['[I130]LastMarriageEndDatePetitioner'])
people_df['[CALCULATED]TotalYearsFromLastMarriagePetitioner']=people_df['[CALCULATED]TotalYearsFromLastMarriagePetitioner']/np.timedelta64(1,'Y')
people_df['[CALCULATED]TotalYearsFromLastMarriagePetitioner'] =round(people_df['[CALCULATED]TotalYearsFromLastMarriagePetitioner'],2)

In [829]:
people_df['[CALCULATED]TotalYearsFromLastMarriageBeneficiary'] = pd.Series.abs(people_df['[I130]DateOfMarriage'] - people_df['[I130]LastMarriageEndDateBeneficiary'])
people_df['[CALCULATED]TotalYearsFromLastMarriageBeneficiary']=people_df['[CALCULATED]TotalYearsFromLastMarriageBeneficiary']/np.timedelta64(1,'Y')
people_df['[CALCULATED]TotalYearsFromLastMarriageBeneficiary']=round(people_df['[CALCULATED]TotalYearsFromLastMarriageBeneficiary'],2)

In [830]:
people_df['[CALCULATED]DiffEntryDateAndMarriageDate']= pd.Series.abs(people_df['[I130]I94DateofEntry']-people_df['[I130]DateOfMarriage'])
people_df['[CALCULATED]DiffEntryDateAndMarriageDate']=people_df['[CALCULATED]DiffEntryDateAndMarriageDate']/np.timedelta64(1,'D')

## 1.3: Dataframe - Properties Check & Conversion to CSV

In [831]:
people_df

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate
0,1300000,Bonnie Reeves,Heather Peters,1988-01-29,1963-03-13,Mississippi,Pakistan,M,2025-01-30,Single,...,2017-01-14,2014-11-06,None,None,3 or 3+ years,4,6,NaN,NaN,800.0
1,1300001,Kimberly Doyle,James Pearson,1971-04-22,1971-02-23,Wisconsin,Chile,F,2023-10-18,Married,...,2016-06-10,2004-08-29,2015-03-12,None,3 or 3+ years,5,17,1.25,NaN,4303.0
2,1300002,Jeffrey Thomas,Christopher Obrien,1987-08-22,1970-09-03,South Dakota,Niger,F,2026-04-27,Divorced,...,2018-05-01,2010-10-19,2017-05-27,2016-08-15,3 or 3+ years,3,11,0.93,1.71,2751.0
3,1300003,Catherine Harrison,Keith Hood,1998-10-18,1982-09-25,Michigan,Estonia,F,2026-02-28,Single,...,2021-06-14,2017-08-23,None,2019-04-01,Under 3 years,0,4,NaN,2.20,1391.0
4,1300004,Grace Gibson,Russell Eaton,1982-08-29,1962-09-04,Arkansas,Ecuador,M,2024-04-12,Single,...,2021-01-30,2014-07-21,None,2018-06-15,3 or 3+ years,0,7,NaN,2.63,2385.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,2021-06-11,2012-12-31,2020-08-18,None,3 or 3+ years,0,8,0.81,NaN,3084.0
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,2016-10-29,2005-08-14,None,None,Under 3 years,4,16,NaN,NaN,4094.0
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,2019-12-10,2014-07-11,None,None,3 or 3+ years,1,7,NaN,NaN,1978.0
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,2017-07-17,2010-05-13,None,2015-09-26,3 or 3+ years,4,11,NaN,1.81,2622.0
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,2017-12-13,2012-05-04,None,2016-09-03,3 or 3+ years,3,9,NaN,1.28,2049.0

In [59]:
people_df.describe(include='all')

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate
count,1.000000e+04,10000,10000,10000,10000,10000,10000,10000,10000,10000,...,10000,10000,3816,3744,10000,10000.000000,10000.000000,3816.000000,3744.000000,10000.000000
unique,NaN,9356,9405,7302,7259,50,194,2,3128,6,...,2263,5075,2001,1985,3,NaN,NaN,NaN,NaN,NaN
top,NaN,Melissa Smith,David Brown,1964-11-16,1988-08-21,Vermont,Botswana,M,2026-06-05,Single,...,2021-06-02,2008-11-26,2017-11-07,2016-06-14,3 or 3+ years,NaN,NaN,NaN,NaN,NaN
freq,NaN,6,6,5,6,235,76,5016,11,5972,...,15,9,6,9,7438,NaN,NaN,NaN,NaN,NaN
mean,1.005000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.364400,9.996600,1.376921,1.382901,2780.648700
std,2.886896e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.752461,4.609416,0.626600,0.617485,1557.931071
min,1.000000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.410000,0.410000,101.000000
25%,1.002500e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,6.000000,0.840000,0.867500,1417.000000
50%,1.005000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.000000,10.000000,1.290000,1.300000,2783.500000
75%,1.007499e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.000000,14.000000,1.870000,1.870000,4128.000000
max,1.009999e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,7.000000,21.000000,2.740000,2.740000,5500.000000

In [650]:
people_df.dtypes

ApplicantID                                                               int64
[I130]PeopleNamePetitioner                                               object
[I130A]PeopleNameBeneficiary                                             object
[I130]DOBPetitioner                                                      object
[I130A]DOBBeneficiary                                                    object
[I130]MailingStateFilingPetitioner                                       object
[I130A]CountryOfBirthBeneficiary                                         object
[I130A]GenderBeneficiary                                                 object
[I130]PassportExpiryBeneficiary                                          object
[I130]PreviousMaritalStatusPetitioner                                    object
[I130]PreviousMaritalStatusBeneficiary                                   object
[I130]PetitionerEthnicity                                                object
[I130]PetitionerRace                                                     object
[I130]PetitionerCitizenStatus                                            object
[I864]RegularIncome                                                       int64
[I864]SupplementalIncome                                                  int64
[I130]StayingTogetherStatus                                              object
[I130]CurrentMaritalStatus                                               object
[I864]FederalTaxFiled                                                    object
[I485-130]SameEmployer                                                   object
[I130]ImmigrationProceeding                                              object
[I485]CriminalityProvedConvicted                                         object
[I130]PreviousPetitionFiledPetitionerSameSpouse                          object
[I130]PreviousPetitionFiledDifferentSpouse                               object
[I130A]BeneficiaryInUS                                                   object
[I130-MarriageCertificate]SamePreparorNoterMinister                      object
[I130]GenderPetitioner                                                   object
[I130]PreviousLegallySeperatedCountryPetitioner                          object
[CALCULATED]AgeGapDays                                          timedelta64[ns]
[CALCULATED]AgePetitioner                                                 int64
[CALCULATED]AgeBeneficiary                                                int64
[CALCULATED]AgeGapYears                                                   int64
[I130]NumberOfMarriagesPetitioner                                         int64
[I130]NumberOfMarriagesBeneficiary                                        int64
[I485]CriminalityProvedConvictedType                                     object
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition                object
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition             object
[I130A]BeneficiaryEthnicity                                              object
[I864]NumberOfDependents                                                  int64
[CALCULATED]FederalPovertyLineValue                                       int64
[CALCULATED]TotalIncome                                                   int64
[I130]DateOfMarriage                                                     object
[I130]I94DateofEntry                                                     object
[I130]LastMarriageEndDatePetitioner                                      object
[I130]LastMarriageEndDateBeneficiary                                     object
[I864]FederalTaxFiledYears                                               object
[CALCULATED]LengthOfMarriage                                              int64
[CALCULATED]YearsSinceDateofEntry                                         int64
[CALCULATED]TotalYearsFromLastMarriagePetitioner                        float64
[CALCULATED]TotalYearsFromLastMarriageBeneficiary                       float64
[CALCULATED]DiffEntryDateAndMarriageDate                                float64
dtype: object

In [265]:
people_df.to_csv('people_df10000T1.csv',index=False)

In [699]:
df1RYG = people_df

In [748]:
df2RYG = people_df

In [788]:
df3RYG = people_df

In [832]:
df4RYG = people_df

In [1121]:
df1RYG.to_csv('df1RYG.csv',index=False)

In [1122]:
df2RYG.to_csv('df2RYG.csv',index=False)

In [1123]:
df3RYG.to_csv('df3RYG.csv',index=False)

In [1124]:
df4RYG.to_csv('df4RYG.csv',index=False)

In [1126]:
maindfRYGT = [df1RYG, df2RYG, df3RYG, df4RYG]

In [1127]:
maindfRYG = pd.concat(maindfRYGT)

In [1128]:
maindfRYG # 200000 Records Random Order

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130A]DOBBeneficiary,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,...,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate
0,1000000,Jessica Smith,Teresa Aguilar,1967-07-06,1968-06-30,Washington,Central African Rep,M,2028-10-30,Single,...,2019-03-10,2018-07-04,None,2018-07-29,NA,2,3,NaN,0.61,249.0
1,1000001,Andre Mccormick,Marcus Gilbert,1971-11-28,1968-01-04,Colorado,Marshall Islands,F,2025-11-29,Divorced,...,2020-09-03,2014-09-17,2019-12-19,None,3 or 3+ years,1,7,0.71,NaN,2178.0
2,1000002,Sarah Gordon,Danielle Contreras,1993-07-02,1966-06-19,Nevada,Cape Verde,M,2024-04-23,Single,...,2018-10-13,2014-04-08,None,None,3 or 3+ years,3,7,NaN,NaN,1649.0
3,1000003,Amber Holloway,Eric Horn,1979-12-06,1978-10-02,Minnesota,Niger,F,2026-03-14,Legally Separated,...,2018-10-06,2018-03-08,2017-10-25,None,NA,3,3,0.95,NaN,212.0
4,1000004,Joseph Smith,Abigail Thomas,1993-12-22,1987-06-24,Minnesota,Sao Tome & Principe,M,2025-08-22,Single,...,2016-06-16,2012-06-20,None,None,3 or 3+ years,5,9,NaN,NaN,1457.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,1996-04-25,New Mexico,Tanzania,M,2029-12-26,Married,...,2021-06-11,2012-12-31,2020-08-18,None,3 or 3+ years,0,8,0.81,NaN,3084.0
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,1985-08-04,Iowa,Suriname,M,2027-04-14,Single,...,2016-10-29,2005-08-14,None,None,Under 3 years,4,16,NaN,NaN,4094.0
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,1987-12-18,Alabama,Paraguay,M,2031-04-10,Single,...,2019-12-10,2014-07-11,None,None,3 or 3+ years,1,7,NaN,NaN,1978.0
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,1995-08-07,North Carolina,Guinea,F,2028-09-24,Single,...,2017-07-17,2010-05-13,None,2015-09-26,3 or 3+ years,4,11,NaN,1.81,2622.0
49999,1349999,David Dickson,Erik Chapman,1969-01-28,1983-05-19,South Carolina,Uzbekistan,M,2026-03-10,Single,...,2017-12-13,2012-05-04,None,2016-09-03,3 or 3+ years,3,9,NaN,1.28,2049.0

In [1129]:
maindfRYG.to_csv('maindfRYGN.csv',index=False)

# 2: Random Data -  Green Flag Prioritized

## 2.1: Generating Independent Attributes

In [1260]:
def make_people2(num):
    
    #CountryOfBirthofSpouse = random.choice(countries_list)
    Faker.seed(84451)

    fake_people2 = [{'ApplicantID':x+3000000,
                  '[I130]PeopleNamePetitioner':fake.name(), 
                  '[I130A]PeopleNameBeneficiary':fake.name(),  
                  '[I130]DOBPetitioner':fake.date_between(start_date='-55y', end_date='-20y'),  
                  #'[I130A]DOBBeneficiary':fake.date_between(start_date='-60y', end_date='-20y'),
                  '[I130]MailingStateFilingPetitioner':random.choice(state_US_list), 
                  '[I130A]CountryOfBirthBeneficiary':random.choice(countries_list),
                  '[I130A]GenderBeneficiary': np.random.choice(["M", "F"], p=[0.5447, 0.4553]),
                  '[I130]PassportExpiryBeneficiary':fake.date_between(start_date='+1y', end_date='+10y'),
                  #'[I130]PreviousMaritalStatusPetitioner': np.random.choice(['Married','Single','Divorced','Widowed','Marriage Anulled','Legally Separated'],p=[0.01,0.95,0.01,0.01,0.01,0.01]),
                  #'[I130]PreviousMaritalStatusBeneficiary':  np.random.choice(['Married','Single','Divorced','Widowed','Marriage Anulled','Legally Separated'],p=[0.01,0.95,0.01,0.01,0.01,0.01]),
                  '[I130]PetitionerEthnicity': np.random.choice(["Hispanic or Latino", "Not Hispanic or Latino", "Not Specified"], p=[0.3, 0.6, 0.1]),
                  '[I130]PetitionerRace':  np.random.choice(["White","Asian","Black or African Ammerican","American Indian or Alaska Native","Native Hawaiian or Other Pacific Islander"]),
                  '[I130]PetitionerCitizenStatus':np.random.choice(["US Citizen","Lawful Permanent Resident"]) , 
                  '[I864]RegularIncome': np.random.choice([random.randint(8000, 20000),random.randint(20000,40000),random.randint(40000, 60000),random.randint(60000,100000),random.randint(100000, 150000),random.randint(150000, 250000),random.randint(250000,1000000)],p=[0.15,0.25,0.30,0.2,0.06,0.03,0.01]),
                  '[I864]SupplementalIncome': np.random.choice([random.randint(0, 8000),random.randint(8000,20000),random.randint(20000, 40000),random.randint(40000,60000),random.randint(60000, 100000),random.randint(100000, 250000),random.randint(250000,1000000)],p=[0.15,0.25,0.30,0.2,0.06,0.03,0.01]),
                  '[I130]StayingTogetherStatus':np.random.choice(["Different States","Same State - Different Address","Same House"],p=[0.04,0.01,0.95]),
                  '[I130]CurrentMaritalStatus':np.random.choice(["Married", "Separated"], p=[0.99, 0.01]),
                  '[I864]FederalTaxFiled':  np.random.choice(["Yes", "No"], p=[0.99, 0.01]),
                  '[I485-130]SameEmployer':np.random.choice(["No", "Yes"], p=[1, 0]),
                  '[I130]ImmigrationProceeding':np.random.choice(["No", "Yes"], p=[0.99, 0.01]),
                  '[I485]CriminalityProvedConvicted':  np.random.choice(["No", "Yes"], p=[0.99, 0.01]),
                  '[I130]PreviousPetitionFiledPetitionerSameSpouse': np.random.choice(["No", "Yes"], p=[1, 0]),
                  '[I130]PreviousPetitionFiledDifferentSpouse': np.random.choice(["No", "Yes"], p=[1, 0]),
                  '[I130A]BeneficiaryInUS': np.random.choice(["Yes", "No"], p=[0.95, 0.05]),
                  '[I130-MarriageCertificate]SamePreparorNoterMinister': np.random.choice(["Yes", "No"], p=[0, 1])  
                   } for x in range(num)]
       
    return fake_people2

In [1261]:
people_df2 = pd.DataFrame(make_people2(num=50000))
people_df2.head(10)

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]StayingTogetherStatus,[I130]CurrentMaritalStatus,[I864]FederalTaxFiled,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I485]CriminalityProvedConvicted,[I130]PreviousPetitionFiledPetitionerSameSpouse,[I130]PreviousPetitionFiledDifferentSpouse,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
5,3000005,Matthew Fisher,David Navarro,1974-06-10,North Carolina,Brunei,F,2031-09-10,Not Hispanic or Latino,Asian,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
6,3000006,Edward Harris,Dawn Powell,1993-07-04,New York,Togo,M,2027-06-29,Not Specified,Black or African Ammerican,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
7,3000007,Brianna Smith,Renee Gardner,1992-08-19,North Dakota,East Timor,F,2028-05-09,Not Hispanic or Latino,Asian,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
8,3000008,Michael Yang,Kelly Riley,1978-10-29,South Dakota,Marshall Islands,F,2028-12-22,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,Same House,Married,Yes,No,No,No,No,No,Yes,No
9,3000009,Paula Alexander,Jennifer Mcdonald,1986-09-21,Tennessee,Laos,M,2022-10-27,Not Hispanic or Latino,White,...,Same House,Married,Yes,No,No,No,No,No,Yes,No

## 2.2: Generating Dependent Attributes

In [68]:
def new_DOB_Petitioner(x):
    edt = x + timedelta(days=3000)
    edt2 = datetime.date(2001,9,20)
    sdt = x - timedelta(days=3000)
    if edt2 > edt:
        dobPetitioner = fake.date_between(start_date=sdt,end_date=edt)
    elif edt >= edt2:
        dobPetitioner = fake.date_between(start_date=sdt,end_date=edt2)
    return dobPetitioner

In [1262]:
people_df2['[I130A]DOBBeneficiary'] =  people_df2['[I130]DOBPetitioner'].apply(lambda x: new_DOB_Petitioner(x))

In [1263]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]CurrentMaritalStatus,[I864]FederalTaxFiled,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I485]CriminalityProvedConvicted,[I130]PreviousPetitionFiledPetitionerSameSpouse,[I130]PreviousPetitionFiledDifferentSpouse,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[I130A]DOBBeneficiary
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,Married,Yes,No,No,No,No,No,Yes,No,1997-08-03
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,Married,Yes,No,No,No,No,No,Yes,No,2000-02-04
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,Married,Yes,No,No,No,No,No,Yes,No,1980-07-26
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,Married,Yes,No,No,No,No,No,Yes,No,1976-06-09
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,Married,Yes,No,No,No,No,No,Yes,No,1978-08-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,Married,Yes,No,No,No,No,No,Yes,No,1974-02-21
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,Married,Yes,No,No,No,No,No,Yes,No,1969-03-20
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,Married,Yes,No,No,No,No,No,Yes,No,1972-09-14
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,Married,Yes,No,No,No,No,No,Yes,No,1973-01-01
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,Married,Yes,No,No,No,No,No,Yes,No,1980-02-04

In [1264]:
people_df2['[I130]GenderPetitioner'] = people_df2['[I130A]GenderBeneficiary'].apply(lambda x: 'M' if x == 'F' else 'F')

In [1265]:
people_df2['[CALCULATED]AgeGapDays'] = pd.Series.abs(people_df2['[I130]DOBPetitioner']-people_df2['[I130A]DOBBeneficiary'])

In [1266]:
people_df2['[CALCULATED]AgePetitioner'] =  people_df2['[I130]DOBPetitioner'].apply(lambda x: from_dob_to_age(x))

In [1267]:
people_df2['[CALCULATED]AgeBeneficiary'] =  people_df2['[I130A]DOBBeneficiary'].apply(lambda x: from_dob_to_age(x))

In [1268]:
people_df2['[CALCULATED]AgeGapYears'] = pd.Series.abs(people_df2['[CALCULATED]AgePetitioner']-people_df2['[CALCULATED]AgeBeneficiary'])

In [1269]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]PreviousPetitionFiledPetitionerSameSpouse,[I130]PreviousPetitionFiledDifferentSpouse,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[I130A]DOBBeneficiary,[I130]GenderPetitioner,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,No,No,Yes,No,1997-08-03,F,380 days,23,24,1
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,No,No,Yes,No,2000-02-04,M,662 days,23,21,2
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,No,No,Yes,No,1980-07-26,F,1527 days,37,41,4
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,No,No,Yes,No,1976-06-09,M,279 days,46,45,1
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,No,No,Yes,No,1978-08-01,M,937 days,40,43,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,No,No,Yes,No,1974-02-21,F,2714 days,40,47,7
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,No,No,Yes,No,1969-03-20,M,2829 days,44,52,8
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,No,No,Yes,No,1972-09-14,M,757 days,47,49,2
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,No,No,Yes,No,1973-01-01,F,1739 days,53,48,5
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,No,No,Yes,No,1980-02-04,F,2760 days,49,41,8

In [1270]:
people_df2['[I130]PreviousMaritalStatusPetitioner'] = people_df2['[CALCULATED]AgePetitioner'].apply(lambda x: np.random.choice(['Single','Marriage Anulled'],p=[0.9,0.1]) if int(x) <= 27 else np.random.choice(['Married','Single','Divorced','Widowed','Marriage Anulled','Legally Separated'],p=[0.01,0.95,0.01,0.01,0.01,0.01]))

In [1271]:
people_df2['[I130]PreviousMaritalStatusBeneficiary'] = people_df2['[CALCULATED]AgeBeneficiary'].apply(lambda x: np.random.choice(['Single','Marriage Anulled'],p=[0.9,0.1]) if int(x) <= 27 else np.random.choice(['Married','Single','Divorced','Widowed','Marriage Anulled','Legally Separated'],p=[0.01,0.95,0.01,0.01,0.01,0.01]))

In [1272]:
people_df2['[I130]PreviousLegallySeperatedCountryPetitioner'] = people_df2['[I130]PreviousMaritalStatusPetitioner'].apply(lambda x: np.random.choice(countries_list,p=[0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.807,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001]) if x == 'Legally Separated' else 'NA')

In [134]:
def number_Of_Marriages2(y,x):
    if y == 'Single' or y == 'Marriage Anulled':
        nom2 = 0
    else:
        if int(x) <= 25 and int(x) >=18:
            nom2 = 1
        elif int(x) > 25 and int(x)<=35:
            nom2 = np.random.choice([random.randint(1,2)])
        elif int(x) > 35 and int(x)<=55:
            nom2 = np.random.choice([random.randint(1,3)])
        elif int(x) > 55:
            nom2 = np.random.choice([random.randint(1,4)])
    return nom2

In [1273]:
people_df2["[I130]NumberOfMarriagesPetitioner"] = people_df2.apply(lambda x : number_Of_Marriages2(x["[I130]PreviousMaritalStatusPetitioner"], x["[CALCULATED]AgePetitioner"]), axis=1)

In [1274]:
people_df2["[I130]NumberOfMarriagesBeneficiary"] = people_df2.apply(lambda x : number_Of_Marriages2(x["[I130]PreviousMaritalStatusBeneficiary"], x["[CALCULATED]AgeBeneficiary"]), axis=1)

In [1275]:
people_df2['[I485]CriminalityProvedConvictedType'] = people_df2['[I485]CriminalityProvedConvicted'].apply(lambda x: np.random.choice(["Minor Reasons", "Major Reasons"], p=[0.999, 0.001]) if x == 'Yes' else 'NA')

In [1276]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[CALCULATED]AgeGapDays,[CALCULATED]AgePetitioner,[CALCULATED]AgeBeneficiary,[CALCULATED]AgeGapYears,[I130]PreviousMaritalStatusPetitioner,[I130]PreviousMaritalStatusBeneficiary,[I130]PreviousLegallySeperatedCountryPetitioner,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,380 days,23,24,1,Single,Single,NA,0,0,NA
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,662 days,23,21,2,Single,Single,NA,0,0,NA
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,1527 days,37,41,4,Single,Single,NA,0,0,NA
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,279 days,46,45,1,Single,Single,NA,0,0,NA
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,937 days,40,43,3,Single,Single,NA,0,0,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,2714 days,40,47,7,Marriage Anulled,Single,NA,0,0,NA
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,2829 days,44,52,8,Married,Single,NA,2,0,NA
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,757 days,47,49,2,Single,Single,NA,0,0,NA
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,1739 days,53,48,5,Single,Married,NA,0,2,NA
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,2760 days,49,41,8,Single,Single,NA,0,0,NA

In [1277]:
people_df2['[I130]PreviousFiledPetitionerSameSpouseRejectionCondition'] = people_df2['[I130]PreviousPetitionFiledPetitionerSameSpouse'].apply(lambda x: np.random.choice(["Minor Reasons", "Moderate Reasons","Major Reasons"], p=[0.98, 0.018,0.002]) if x == 'Yes' else 'NA')

In [1278]:
people_df2['[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition'] = people_df2['[I130]PreviousPetitionFiledDifferentSpouse'].apply(lambda x: np.random.choice(["Minor Reasons", "Moderate Reasons","Major Reasons"], p=[0.98, 0.018,0.002]) if x == 'Yes' else 'NA')

In [1279]:
people_df2['[I130A]BeneficiaryEthnicity'] =  people_df2['[I130A]CountryOfBirthBeneficiary'].apply(lambda x: find_ethnicity(x))

In [88]:
def number_of_Dependents2(x,y,p,q):
    if p == 0 and q == 0:
        numberOfDependents = np.random.choice([random.randint(1,2)])
    elif p > 0 or q > 0:
        if x> 45 or y > 45:
            numberOfDependents = np.random.choice([random.randint(2,4)])
        elif x<=45 and x>=30:
            if y>=30 and y<=45:
                numberOfDependents = np.random.choice([random.randint(1,3)])
            elif y<30:
                numberOfDependents = np.random.choice([random.randint(1,2)])
        elif x<30:
            if y>=30 and y<=45:
                numberOfDependents = np.random.choice([random.randint(1,2)])
            elif y<30:
                numberOfDependents = np.random.choice([random.randint(1,2)])
    return numberOfDependents

In [1280]:
people_df2["[I864]NumberOfDependents"] = people_df2.apply(lambda x : number_of_Dependents2(x["[CALCULATED]AgePetitioner"], x["[CALCULATED]AgeBeneficiary"], x["[I130]NumberOfMarriagesPetitioner"], x["[I130]NumberOfMarriagesBeneficiary"]), axis=1)

In [1281]:
people_df2['[CALCULATED]FederalPovertyLineValue'] = people_df2.apply(lambda x : federalpovertyline_calculator(x['[I864]NumberOfDependents'], x['[I130]MailingStateFilingPetitioner']), axis=1)

In [1282]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]PreviousMaritalStatusBeneficiary,[I130]PreviousLegallySeperatedCountryPetitioner,[I130]NumberOfMarriagesPetitioner,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[I130A]BeneficiaryEthnicity,[I864]NumberOfDependents,[CALCULATED]FederalPovertyLineValue
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,1,21775
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,2,27450
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,1,21775
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,2,27450
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,2,27450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,1,21775
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,Single,NA,2,0,NA,NA,NA,Not Hispanic or Latino,3,38100
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,2,27450
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,Married,NA,0,2,NA,NA,NA,Not Hispanic or Latino,2,27450
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,Single,NA,0,0,NA,NA,NA,Not Hispanic or Latino,1,21775

In [1283]:
people_df2['[CALCULATED]TotalIncome'] = people_df2['[I864]RegularIncome'] + people_df2['[I864]SupplementalIncome']

In [147]:
def dateOfMarriageGr(x,y):
    if int(x)>=45 and int(y) >= 45:
        firstdateSet = datetime.date(2010,9,20)
        enddateSet = datetime.date(2016,7,20)
    elif (int(x)>=30 and int(x)<45) or (int(y)>=30 and int(y)<45):   
        firstdateSet = datetime.date(2014,9,20)
        enddateSet = datetime.date(2017,7,20)
    elif (int(x)>=25 and int(x)<30) or (int(y)>=25 and int(y)<30):   
        firstdateSet = datetime.date(2016,9,20)
        enddateSet = datetime.date(2018,7,20)
    elif (int(x)>=22 and int(x)<25) or (int(y)>=22 and int(y)<25):
        firstdateSet = datetime.date(2017,10,20)
        enddateSet = datetime.date(2019,7,20)
    elif int(x)<22 or int(y)<22:    
        firstdateSet = datetime.date(2019,10,20)
        enddateSet = datetime.date(2020,7,20)
    return fake.date_between(start_date=firstdateSet, end_date=enddateSet)

In [1284]:
people_df2['[I130]DateOfMarriage'] = people_df2.apply(lambda x : dateOfMarriageGr(x['[CALCULATED]AgePetitioner'], x['[CALCULATED]AgeBeneficiary']), axis=1)

In [120]:
def I94DateM2(x):
    edt = x - timedelta(days=800)
    sdt = x - timedelta(days=5000)
    return fake.date_between(start_date=sdt,end_date=edt)

In [1285]:
people_df2['[I130]I94DateofEntry'] =  people_df2['[I130]DateOfMarriage'].apply(lambda x: I94DateM2(x))

In [1286]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]NumberOfMarriagesBeneficiary,[I485]CriminalityProvedConvictedType,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[I130A]BeneficiaryEthnicity,[I864]NumberOfDependents,[CALCULATED]FederalPovertyLineValue,[CALCULATED]TotalIncome,[I130]DateOfMarriage,[I130]I94DateofEntry
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,0,NA,NA,NA,Not Hispanic or Latino,1,21775,74705,2018-12-19,2008-09-29
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,0,NA,NA,NA,Not Hispanic or Latino,2,27450,59632,2018-07-11,2008-12-25
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,0,NA,NA,NA,Not Hispanic or Latino,1,21775,120470,2017-05-10,2007-12-17
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,0,NA,NA,NA,Not Hispanic or Latino,2,27450,89214,2011-07-03,2001-10-23
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,0,NA,NA,NA,Not Hispanic or Latino,2,27450,60074,2016-10-29,2007-09-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,0,NA,NA,NA,Not Hispanic or Latino,1,21775,125516,2016-01-20,2003-09-25
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,0,NA,NA,NA,Not Hispanic or Latino,3,38100,45631,2015-04-05,2009-07-31
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,0,NA,NA,NA,Not Hispanic or Latino,2,27450,38130,2012-02-26,2009-08-31
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,2,NA,NA,NA,Not Hispanic or Latino,2,27450,39679,2016-06-05,2005-02-11
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,0,NA,NA,NA,Not Hispanic or Latino,1,21775,248625,2015-12-02,2010-09-05

In [160]:
def lastMarriageDate2(x,y,z):
    if int(x) >= 25 and int(x)<30 and int(z)>=1:
        sdlm= y - timedelta(days=1000)
        edlm= y - timedelta(days=740)
        lmdate = fake.date_between(start_date=sdlm,end_date=edlm)
        return lmdate
    elif int(x) >= 30 and int(x)<45 and int(z)>=1:
        sdlm= y - timedelta(days=1200)
        edlm= y - timedelta(days=750)
        lmdate = fake.date_between(start_date=sdlm,end_date=edlm)
        return lmdate
    elif int(x) >= 45 and int(z)>=1:
        sdlm= y - timedelta(days=1500)
        edlm= y - timedelta(days=800)
        lmdate = fake.date_between(start_date=sdlm,end_date=edlm)
        return lmdate

In [1287]:
people_df2['[I130]LastMarriageEndDatePetitioner'] = people_df2.apply(lambda x : lastMarriageDate2(x['[CALCULATED]AgePetitioner'], x['[I130]DateOfMarriage'], x['[I130]NumberOfMarriagesPetitioner']), axis=1)

In [1288]:
people_df2['[I130]LastMarriageEndDateBeneficiary'] = people_df2.apply(lambda x : lastMarriageDate2(x['[CALCULATED]AgeBeneficiary'], x['[I130]DateOfMarriage'], x['[I130]NumberOfMarriagesBeneficiary']), axis=1)

In [154]:
def federalTaxNumberYears2(x,y):
    if y=="Yes":
        if int(x) == 20:
            years = np.random.choice([1,2,3], p=[0.35, 0.55,0.1])
        elif int(x) > 20 and int(x) < 22:
            years = np.random.choice([1,2,3], p=[0.1, 0.2,0.7])
        elif int(x) >= 22 and int(x)< 30:
            years = np.random.choice([1,2,3,4], p=[0.01,0.01,0.34,0.64])
        elif int(x) >= 30:
            years = np.random.choice([1,2,3,4], p=[0.001,0.01,0.14,0.849])
        
    if y == "No":
        value = "NA"
    elif years >= 3:
        value = "3 or 3+ years"
    elif years >=1 and years < 3:
        value = "Under 3 years"
        
    return value

In [1289]:
people_df2['[I864]FederalTaxFiledYears'] = people_df2.apply(lambda x : federalTaxNumberYears2(x['[CALCULATED]AgePetitioner'], x['[I864]FederalTaxFiled']), axis=1)

In [1290]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[I130A]BeneficiaryEthnicity,[I864]NumberOfDependents,[CALCULATED]FederalPovertyLineValue,[CALCULATED]TotalIncome,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,NA,Not Hispanic or Latino,1,21775,74705,2018-12-19,2008-09-29,None,None,3 or 3+ years
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,NA,Not Hispanic or Latino,2,27450,59632,2018-07-11,2008-12-25,None,None,3 or 3+ years
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,NA,Not Hispanic or Latino,1,21775,120470,2017-05-10,2007-12-17,None,None,3 or 3+ years
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,NA,Not Hispanic or Latino,2,27450,89214,2011-07-03,2001-10-23,None,None,3 or 3+ years
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,NA,Not Hispanic or Latino,2,27450,60074,2016-10-29,2007-09-09,None,None,3 or 3+ years
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,NA,Not Hispanic or Latino,1,21775,125516,2016-01-20,2003-09-25,None,None,3 or 3+ years
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,NA,Not Hispanic or Latino,3,38100,45631,2015-04-05,2009-07-31,2012-07-30,None,3 or 3+ years
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,NA,Not Hispanic or Latino,2,27450,38130,2012-02-26,2009-08-31,None,None,3 or 3+ years
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,NA,Not Hispanic or Latino,2,27450,39679,2016-06-05,2005-02-11,None,2012-06-22,3 or 3+ years
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,NA,Not Hispanic or Latino,1,21775,248625,2015-12-02,2010-09-05,None,None,3 or 3+ years

In [1291]:
people_df2['[CALCULATED]LengthOfMarriage'] =  people_df2['[I130]DateOfMarriage'].apply(lambda x: from_dob_to_age(x))

In [1292]:
people_df2['[CALCULATED]YearsSinceDateofEntry'] =  people_df2['[I130]I94DateofEntry'].apply(lambda x: from_dob_to_age(x))

In [1293]:
people_df2['[CALCULATED]TotalYearsFromLastMarriagePetitioner'] = pd.Series.abs(people_df2['[I130]DateOfMarriage'] - people_df2['[I130]LastMarriageEndDatePetitioner'])
people_df2['[CALCULATED]TotalYearsFromLastMarriagePetitioner']=people_df2['[CALCULATED]TotalYearsFromLastMarriagePetitioner']/np.timedelta64(1,'Y')
people_df2['[CALCULATED]TotalYearsFromLastMarriagePetitioner'] =round(people_df2['[CALCULATED]TotalYearsFromLastMarriagePetitioner'],2)

In [1294]:
people_df2['[CALCULATED]TotalYearsFromLastMarriageBeneficiary'] = pd.Series.abs(people_df2['[I130]DateOfMarriage'] - people_df2['[I130]LastMarriageEndDateBeneficiary'])
people_df2['[CALCULATED]TotalYearsFromLastMarriageBeneficiary']=people_df2['[CALCULATED]TotalYearsFromLastMarriageBeneficiary']/np.timedelta64(1,'Y')
people_df2['[CALCULATED]TotalYearsFromLastMarriageBeneficiary']=round(people_df2['[CALCULATED]TotalYearsFromLastMarriageBeneficiary'],2)

In [1295]:
people_df2['[CALCULATED]DiffEntryDateAndMarriageDate']= pd.Series.abs(people_df2['[I130]I94DateofEntry']-people_df2['[I130]DateOfMarriage'])
people_df2['[CALCULATED]DiffEntryDateAndMarriageDate']=people_df2['[CALCULATED]DiffEntryDateAndMarriageDate']/np.timedelta64(1,'D')

In [1296]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,2018-12-19,2008-09-29,None,None,3 or 3+ years,2,13,NaN,NaN,3733.0
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,2018-07-11,2008-12-25,None,None,3 or 3+ years,3,12,NaN,NaN,3485.0
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,2017-05-10,2007-12-17,None,None,3 or 3+ years,4,13,NaN,NaN,3432.0
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,2011-07-03,2001-10-23,None,None,3 or 3+ years,10,19,NaN,NaN,3540.0
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,2016-10-29,2007-09-09,None,None,3 or 3+ years,4,14,NaN,NaN,3338.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,2016-01-20,2003-09-25,None,None,3 or 3+ years,5,18,NaN,NaN,4500.0
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,2015-04-05,2009-07-31,2012-07-30,None,3 or 3+ years,6,12,2.68,NaN,2074.0
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,2012-02-26,2009-08-31,None,None,3 or 3+ years,9,12,NaN,NaN,909.0
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,2016-06-05,2005-02-11,None,2012-06-22,3 or 3+ years,5,16,NaN,3.95,4132.0
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,2015-12-02,2010-09-05,None,None,3 or 3+ years,5,11,NaN,NaN,1914.0

## 2.3: Dataframe - Properties Check & Conversion to CSV

In [1297]:
people_df2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate
0,3000000,Richard Lee,Derrick Raymond,1998-08-18,Delaware,Zimbabwe,M,2030-09-19,Not Hispanic or Latino,American Indian or Alaska Native,...,2018-12-19,2008-09-29,None,None,3 or 3+ years,2,13,NaN,NaN,3733.0
1,3000001,Spencer Taylor,Angel Lane,1998-04-13,Indiana,Nigeria,F,2027-09-18,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,2018-07-11,2008-12-25,None,None,3 or 3+ years,3,12,NaN,NaN,3485.0
2,3000002,Anthony Morrison,Henry Shields,1984-09-30,Illinois,Chad,M,2029-11-21,Hispanic or Latino,American Indian or Alaska Native,...,2017-05-10,2007-12-17,None,None,3 or 3+ years,4,13,NaN,NaN,3432.0
3,3000003,Jennifer Miller,Edward Reid,1975-09-04,Vermont,Gambia,F,2028-06-09,Not Specified,White,...,2011-07-03,2001-10-23,None,None,3 or 3+ years,10,19,NaN,NaN,3540.0
4,3000004,David Barber,Jessica Elliott,1981-02-23,New Hampshire,Brunei,F,2031-02-08,Hispanic or Latino,Asian,...,2016-10-29,2007-09-09,None,None,3 or 3+ years,4,14,NaN,NaN,3338.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,2016-01-20,2003-09-25,None,None,3 or 3+ years,5,18,NaN,NaN,4500.0
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,2015-04-05,2009-07-31,2012-07-30,None,3 or 3+ years,6,12,2.68,NaN,2074.0
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,2012-02-26,2009-08-31,None,None,3 or 3+ years,9,12,NaN,NaN,909.0
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,2016-06-05,2005-02-11,None,2012-06-22,3 or 3+ years,5,16,NaN,3.95,4132.0
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,2015-12-02,2010-09-05,None,None,3 or 3+ years,5,11,NaN,NaN,1914.0

In [168]:
people_df2.describe(include='all')

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PreviousMaritalStatusPetitioner,[I130]PreviousMaritalStatusBeneficiary,...,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate
count,1.000000e+04,10000,10000,10000,10000,10000,10000,10000,10000,10000,...,10000,10000,325,317,10000,10000.000000,10000.00000,325.000000,317.000000,10000.000000
unique,NaN,9402,9411,6905,50,194,2,3140,6,6,...,2652,4506,296,298,3,NaN,NaN,NaN,NaN,NaN
top,NaN,Michael Williams,Christopher Smith,1997-01-29,South Carolina,Togo,M,2025-03-12,Single,Single,...,2017-01-11,2011-07-10,2013-01-21,2013-11-29,3 or 3+ years,NaN,NaN,NaN,NaN,NaN
freq,NaN,8,7,6,228,73,5011,12,9396,9382,...,17,8,3,2,9463,NaN,NaN,NaN,NaN,NaN
mean,1.005000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.313400,13.27790,2.835969,2.809495,2904.235300
std,2.886896e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.841934,3.76283,0.507221,0.509338,1207.515385
min,1.000000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,3.00000,2.050000,2.060000,801.000000
25%,1.002500e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.000000,10.00000,2.430000,2.400000,1866.000000
50%,1.005000e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5.000000,13.00000,2.760000,2.710000,2909.000000
75%,1.007499e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.000000,16.00000,3.150000,3.140000,3943.250000
max,1.009999e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11.000000,24.00000,4.090000,4.100000,5000.000000

In [169]:
people_df2.dtypes

ApplicantID                                                               int64
[I130]PeopleNamePetitioner                                               object
[I130A]PeopleNameBeneficiary                                             object
[I130]DOBPetitioner                                                      object
[I130]MailingStateFilingPetitioner                                       object
[I130A]CountryOfBirthBeneficiary                                         object
[I130A]GenderBeneficiary                                                 object
[I130]PassportExpiryBeneficiary                                          object
[I130]PreviousMaritalStatusPetitioner                                    object
[I130]PreviousMaritalStatusBeneficiary                                   object
[I130]PetitionerEthnicity                                                object
[I130]PetitionerRace                                                     object
[I130]PetitionerCitizenStatus                                            object
[I864]RegularIncome                                                       int64
[I864]SupplementalIncome                                                  int64
[I130]StayingTogetherStatus                                              object
[I130]CurrentMaritalStatus                                               object
[I864]FederalTaxFiled                                                    object
[I485-130]SameEmployer                                                   object
[I130]ImmigrationProceeding                                              object
[I485]CriminalityProvedConvicted                                         object
[I130]PreviousPetitionFiledPetitionerSameSpouse                          object
[I130]PreviousPetitionFiledDifferentSpouse                               object
[I130A]BeneficiaryInUS                                                   object
[I130-MarriageCertificate]SamePreparorNoterMinister                      object
[I130A]DOBBeneficiary                                                    object
[I130]GenderPetitioner                                                   object
[I130]PreviousLegallySeperatedCountryPetitioner                          object
[CALCULATED]AgeGapDays                                          timedelta64[ns]
[CALCULATED]AgePetitioner                                                 int64
[CALCULATED]AgeBeneficiary                                                int64
[CALCULATED]AgeGapYears                                                   int64
[I130]NumberOfMarriagesPetitioner                                         int64
[I130]NumberOfMarriagesBeneficiary                                        int64
[I485]CriminalityProvedConvictedType                                     object
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition                object
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition             object
[I130A]BeneficiaryEthnicity                                              object
[I864]NumberOfDependents                                                  int64
[CALCULATED]FederalPovertyLineValue                                       int64
[CALCULATED]TotalIncome                                                   int64
[I130]DateOfMarriage                                                     object
[I130]I94DateofEntry                                                     object
[I130]LastMarriageEndDatePetitioner                                      object
[I130]LastMarriageEndDateBeneficiary                                     object
[I864]FederalTaxFiledYears                                               object
[CALCULATED]LengthOfMarriage                                              int64
[CALCULATED]YearsSinceDateofEntry                                         int64
[CALCULATED]TotalYearsFromLastMarriagePetitioner                        float64
[CALCULATED]TotalYearsFromLastMarriageBeneficiary                       float64
[CALCULATED]DiffEntryDateAndMarriageDate                                float64
dtype: object

In [170]:
people_df2.to_csv('people_df210000T1.csv',index=False)

In [171]:
len(people_df2)

10000

In [877]:
df1YG = people_df2

In [916]:
df2YG = people_df2

In [958]:
df3YG = people_df2

In [997]:
df4YG = people_df2

In [1040]:
df5YG = people_df2

In [1081]:
df6YG = people_df2

In [1120]:
df7YG = people_df2

In [1175]:
df8YG = people_df2

In [1215]:
df9YG = people_df2

In [1257]:
df10YG = people_df2

In [1298]:
df11YG = people_df2

In [1130]:
df1YG.to_csv('df1YG.csv',index=False)

In [1131]:
df2YG.to_csv('df2YG.csv',index=False)

In [1132]:
df3YG.to_csv('df3YG.csv',index=False)

In [1133]:
df4YG.to_csv('df4YG.csv',index=False)

In [1134]:
df5YG.to_csv('df5YG.csv',index=False)

In [1135]:
df6YG.to_csv('df6YG.csv',index=False)

In [1136]:
df7YG.to_csv('df7YG.csv',index=False)

In [1176]:
df8YG.to_csv('df8YG.csv',index=False)

In [1216]:
df9YG.to_csv('df9YG.csv',index=False)

In [1258]:
df10YG.to_csv('df10YG.csv',index=False)

In [1299]:
df11YG.to_csv('df11YG.csv',index=False)

In [1300]:
maindfYGT = [df1YG, df2YG, df3YG, df4YG, df5YG, df6YG, df7YG, df8YG, df9YG, df10YG, df11YG]

In [1301]:
maindfYG = pd.concat(maindfYGT)

In [1302]:
maindfYG

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]DateOfMarriage,[I130]I94DateofEntry,[I130]LastMarriageEndDatePetitioner,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate
0,2000000,Jessica Smith,Teresa Aguilar,1972-07-05,Connecticut,Albania,M,2024-06-21,Not Hispanic or Latino,American Indian or Alaska Native,...,2015-08-03,2010-05-28,None,None,3 or 3+ years,6,11,NaN,NaN,1893.0
1,2000001,Cynthia Johnson,Hannah Hanson,1998-05-05,Utah,Gabon,M,2025-04-29,Not Hispanic or Latino,American Indian or Alaska Native,...,2015-03-10,2008-07-09,None,None,3 or 3+ years,6,13,NaN,NaN,2435.0
2,2000002,Micheal Bruce,Shirley Wright,1998-07-02,New Hampshire,Croatia,F,2023-12-19,Not Hispanic or Latino,White,...,2017-08-16,2007-06-10,None,None,3 or 3+ years,4,14,NaN,NaN,3720.0
3,2000003,Ann Riley,Justin Newman,1999-07-14,North Dakota,Iran,F,2028-11-03,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,2018-05-25,2005-12-14,None,None,3 or 3+ years,3,15,NaN,NaN,4545.0
4,2000004,Matthew Gonzalez,Mary David,1971-08-08,Wisconsin,Togo,F,2022-11-23,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,2015-10-14,2005-03-29,None,None,3 or 3+ years,6,16,NaN,NaN,3851.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,3049995,Jeremy Mckay,Haley Roberts,1981-07-28,Kentucky,Liechtenstein,M,2028-08-30,Not Hispanic or Latino,Black or African Ammerican,...,2016-01-20,2003-09-25,None,None,3 or 3+ years,5,18,NaN,NaN,4500.0
49996,3049996,Ricky Krueger,Kevin Taylor,1976-12-17,Hawaii,Mozambique,F,2030-10-04,Hispanic or Latino,White,...,2015-04-05,2009-07-31,2012-07-30,None,3 or 3+ years,6,12,2.68,NaN,2074.0
49997,3049997,Edward Mack,Stephen Long,1974-10-11,Colorado,Uzbekistan,F,2025-06-15,Hispanic or Latino,Black or African Ammerican,...,2012-02-26,2009-08-31,None,None,3 or 3+ years,9,12,NaN,NaN,909.0
49998,3049998,Destiny Patterson,Michael Thompson,1968-03-29,North Carolina,Bosnia Herzegovina,M,2028-05-25,Hispanic or Latino,Asian,...,2016-06-05,2005-02-11,None,2012-06-22,3 or 3+ years,5,16,NaN,3.95,4132.0
49999,3049999,Suzanne Johnson,Keith Berger,1972-07-15,Texas,Trinidad & Tobago,M,2028-07-08,Hispanic or Latino,White,...,2015-12-02,2010-09-05,None,None,3 or 3+ years,5,11,NaN,NaN,1914.0

In [1303]:
maindfYG.to_csv('maindfYG.csv',index=False)

# Part 3: Fraud Class

In [250]:
maindf = [people_df2, people_df]

In [251]:
combPeopledf = pd.concat(maindf)

In [1304]:
combPeopledfSave = combPeopledf

In [1305]:
maindfNew = [maindfYG, maindfRYG]

In [1306]:
combPeopledf = pd.concat(maindfNew)

In [605]:
def main():
    combPeopledf['[Calculated]FlagType']=''
    combPeopledf['[Calculated]FraudLikelihood']=''
    combPeopledf['[Calculated]FraudDescriptive']=''
    for i in range(len(combPeopledf)): 
        ##################################### Checking Staying Together Status #####################################
        checkVal1 = combPeopledf['[I130]StayingTogetherStatus'].values[i]
        if checkVal1 == "Same State - Different Address":
            a=2
        elif checkVal1 == "Different States":
            a=1
        elif checkVal1 == "Same House":
            a=0
        
        if a == 2:
            combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Same State - Different Address; "
        elif a == 1:
            combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
            combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Different State; "
        elif a == 0:
            combPeopledf['[Calculated]FlagType'].values[i] = "Green"
            combPeopledf['[Calculated]FraudLikelihood'].values[i] = "No"
            combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        
        primeValCheck = a    # Counter to ensure Red remains Red, Yellow remains Yellow, unless a Red Flag comes along
                             # Ensures priority/severity order: Red > Yellow > Green
        
        ##################################### Checking Immigration Proceeding #####################################
        checkVal2 = combPeopledf['[I130]ImmigrationProceeding'].values[i]
        if checkVal2 == "Yes":
            b=2
        elif checkVal2 == "No":
            b=0
        
        if primeValCheck==2:
            if b == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Immigration Proceeding; "
            elif b == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if b == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Immigration Proceeding; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif b == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if b == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Immigration Proceeding; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif b == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        
        ##################################### Checking Same Employer #####################################
        checkVal3 = combPeopledf['[I485-130]SameEmployer'].values[i]
        if checkVal3 == "Yes":
            c=2
        elif checkVal3 == "No":
            c=0
        
        if primeValCheck==2:
            if c == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Same Employer; "
            elif c == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if c == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Same Employer; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif c == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if c == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Same Employer; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif c == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""

        ##################################### Checking Same Preparer/Noter/Minister #####################################
        checkVal4 = combPeopledf['[I130-MarriageCertificate]SamePreparorNoterMinister'].values[i]
        if checkVal4 == "Yes":
            d=2
        elif checkVal4 == "No":
            d=0
        
        if primeValCheck==2:
            if d == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Same Preparer/Noter/Minister; "
            elif d == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if d == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Same Preparer/Noter/Minister; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif d == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if d == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Same Preparer/Noter/Minister; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif d == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
                
        ##################################### Checking Criminality #####################################
        checkVal5 = combPeopledf['[I485]CriminalityProvedConvictedType'].values[i]
        if checkVal5 == "Major Reasons":
            e=2
        elif checkVal5 == "Minor Reasons":
            e=1
        elif checkVal5!="Major Reasons" and checkVal5!="Minor Reasons":
            e=0
        
        if primeValCheck==2:
            if e == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Criminal Record - Major; "
            elif e==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Criminal Record - Minor; "
            elif e == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if e == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Criminal Record - Major; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif e==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Criminal Record - Minor; "
            elif e == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if e == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Criminal Record - Major; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif e==1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Criminal Record - Minor; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif e == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "" 
                
        ##################################### Checking Current Marital Status #####################################
        checkVal6 = combPeopledf['[I130]CurrentMaritalStatus'].values[i]
        if checkVal6 == "Separated":
            f=1
        elif checkVal6 == "Married":
            f=0
        
        if primeValCheck==2:
            if f == 1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Marital Status - Not Married; "            
            elif f == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if f == 1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Marital Status - Not Married; "
            elif f == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if f == 1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Marital Status - Not Married; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif f == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
                
        ##################################### Checking Beneficiary in US #####################################
        checkVal7 = combPeopledf['[I130A]BeneficiaryInUS'].values[i]
        if checkVal7 == "No":
            g=1
        elif checkVal7 == "Yes":
            g=0
        
        if primeValCheck==2:
            if g == 1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Beneficiary not in US; "            
            elif g == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if g == 1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Beneficiary not in US; "
            elif g == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if g == 1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Beneficiary not in US; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif g == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        
        
        
        ##################################### Checking Age Gap Years #####################################
        checkVal8 = combPeopledf['[CALCULATED]AgeGapYears'].values[i]
        if checkVal8 >= 15:
            h=2
        elif checkVal8 >= 9 and checkVal8 < 15:
            h=1
        elif checkVal8 < 9:
            h=0
        
        if primeValCheck==2:
            if h == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Age Gap greater than 15 years; "
            elif h==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Age Gap in between 9 - 15 years; "
            elif h == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if h == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Age Gap greater than 15 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif h==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Age Gap in between 9 - 15 years; "
            elif h == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if h == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Age Gap greater than 15 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif h==1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Age Gap in between 9 - 15 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif h == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "" 
        ##################################### Checking Income eligibility #####################################
        checkVal9 = combPeopledf['[CALCULATED]TotalIncome'].values[i]
        checkVal10 = combPeopledf['[CALCULATED]FederalPovertyLineValue'].values[i]
        if checkVal9 < checkVal10:
            j=2
        elif checkVal9 >= checkVal10 :
            j=0
            
        if primeValCheck==2:
            if j == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Total Income less than Federal Poverty Line; "
            elif j == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if j == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Total Income less than Federal Poverty Line; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif j == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if j == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Total Income less than Federal Poverty Line; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif j == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        
        
        ##################################### Checking Federal Tax #####################################
        checkVal11 = combPeopledf['[I864]FederalTaxFiledYears'].values[i]
        checkVal12 = combPeopledf['[CALCULATED]AgePetitioner'].values[i]
        
        if checkVal12 >=23:
            if checkVal11 == "3 or 3+ years":
                k=0
            elif checkVal11 == "Under 3 years":
                k=1
            elif checkVal11 == "NA":
                k=2
        elif checkVal12 <23:
            if checkVal11 == "3 or 3+ years":
                k=0
            elif checkVal11 == "Under 3 years":
                k=1
            elif checkVal11 == "NA":
                k=4
         
        if primeValCheck==2:
            if k == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: No Federal Tax Documentation Provided; "
            elif k==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Less than 3 years of Federal Tax Years Filed; "
            elif k==4:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: No Federal Tax Files Records & Age less than 22 years; "
            elif k == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if k == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: No Federal Tax Documentation Provided; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif k==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Less than 3 years of Federal Tax Years Filed; "
            elif k==4:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: No Federal Tax Files Records & Age less than 22 years; "
            elif k == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if k == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: No Federal Tax Documentation Provided; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif k==1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Less than 3 years of Federal Tax Years Filed; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif k==4:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: No Federal Tax Files Records & Age less than 22 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif k == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""         
        
        ##################################### Checking Last Marriage End #####################################
        checkVal14 = combPeopledf['[CALCULATED]TotalYearsFromLastMarriagePetitioner'].values[i]
        checkVal15 = combPeopledf['[CALCULATED]TotalYearsFromLastMarriageBeneficiary'].values[i]
        
        if checkVal14 >= 2:
            l1=0
        elif checkVal14 < 2:
            l1=2
        else:
            l1=0
        
        if checkVal15 >= 2:
            l2=0
        elif checkVal15 < 2:
            l2=2
        else:
            l2=0
        
        if primeValCheck==2:
            if l1 == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Petitioner - Less than 2 years from Last Marriage; "
            elif l1 == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if l1 == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Petitioner - Less than 2 years from Last Marriage; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif l1 == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if l1 == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Petitioner - Less than 2 years from Last Marriage; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif l1 == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
                
        if primeValCheck==2:
            if l2 == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Beneficiary - Less than 2 years from Last Marriage; "
            elif l2 == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if l2 == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Beneficiary - Less than 2 years from Last Marriage; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif l2 == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if l2 == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Beneficiary - Less than 2 years from Last Marriage; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif l2 == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        ##################################### Checking Marriage History #####################################
        checkVal16 = combPeopledf['[CALCULATED]LengthOfMarriage'].values[i]
        checkVal17 = combPeopledf['[CALCULATED]AgeBeneficiary'].values[i]
        #checkVal12 =[CALCULATED]AgePetitioner
        
        if checkVal17 <=22 or checkVal12 <=22:
            if checkVal16 >=2:
                m=0
            elif checkVal16 <=2:
                m=4
        elif checkVal17 > 22 and checkVal12 > 22:
            if checkVal16 >=3:
                m=0
            elif checkVal16 >=2 and checkVal16 < 3:
                m=1
            elif checkVal16 < 2:
                m=2
        
        if primeValCheck==2:
            if m== 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Length of Marriage less than 2 years; "
            elif m==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Length of Marriage in between 2-3 years; "
            elif m==4:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Length of Marriage less than 2 years and Individual's Age less than 22 Years; "
            elif m == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if m==2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Length of Marriage less than 2 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif m==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Length of Marriage in between 2-3 years; "
            elif m==4:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Length of Marriage less than 2 years and Individual's Age less than 22 Years; "
            elif m == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if m == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Length of Marriage less than 2 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif m==1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Length of Marriage in between 2-3 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif m==4:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Length of Marriage less than 2 years and Individual's Age less than 22 Years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif m == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        
        ##################################### Checking Gap Between Entry and Mariage #####################################
        checkVal18 = combPeopledf['[CALCULATED]DiffEntryDateAndMarriageDate'].values[i]
        
        if checkVal18 <= 180:
            n=2
        elif checkVal18 > 180 and checkVal18 <= 730:
            n=1
        elif checkVal18 >= 731:
            n=0
            
        if primeValCheck==2:
            if n == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Difference between Entry Date and Marriage Date is less than 6 months; "
            elif n==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Difference between Entry Date and Marriage Date is in between 6 months - 2 years; "
            elif n == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if n == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Difference between Entry Date and Marriage Date is less than 6 months; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif n==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Difference between Entry Date and Marriage Date is in between 6 months - 2 years; "
            elif n == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if n == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Difference between Entry Date and Marriage Date is less than 6 months; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif n==1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Difference between Entry Date and Marriage Date is in between 6 months - 2 years; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif n == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "" 
        
        
        ##################################### Checking Previous Filed Petition #####################################
        checkVal19 = combPeopledf['[I130]PreviousFiledPetitionerSameSpouseRejectionCondition'].values[i]
        checkVal20 = combPeopledf['[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition'].values[i]
        
        if checkVal19 == "Major Reasons":
            p=2
        elif checkVal19 == "Moderate Reasons":
            p=1
        elif checkVal19!="Major Reasons" and checkVal19!="Moderate Reasons":
            p=0
        
        
        if primeValCheck==2:
            if p == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Previous Filed Petitioner Same Spouse Rejection Condition: Major Reasons; "
            elif p==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Previous Filed Petitioner Same Spouse Rejection Condition: Moderate Reasons; "
            elif p == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if p == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Previous Filed Petitioner Same Spouse Rejection Condition: Major Reasons; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif p==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Previous Filed Petitioner Same Spouse Rejection Condition: Moderate Reasons; "
            elif p == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if p == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Previous Filed Petitioner Same Spouse Rejection Condition: Major Reasons; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif p==1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Previous Filed Petitioner Same Spouse Rejection Condition: Moderate Reasons; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif p == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "" 
        
        if checkVal20 == "Major Reasons":
            q=2
        elif checkVal20 == "Moderate Reasons":
            q=1
        elif checkVal20!="Major Reasons" and checkVal20!="Moderate Reasons":
            q=0
            
        if primeValCheck==2:
            if q == 2:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Previous Filed Petitioner Different Spouse Rejection Condition: Major Reasons; "
            elif q==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Previous Filed Petitioner Different Spouse Rejection Condition: Moderate Reasons; "
            elif q == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==1:
            if q == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Previous Filed Petitioner Different Spouse Rejection Condition: Major Reasons; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
            elif q==1:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Previous Filed Petitioner Different Spouse Rejection Condition: Moderate Reasons; "
            elif q == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""
        elif primeValCheck==0:
            if q == 2:
                primeValCheck = 2
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Red Flag: Previous Filed Petitioner Different Spouse Rejection Condition: Major Reasons; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Red"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif q==1:
                primeValCheck = 1
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += "Yellow Flag: Previous Filed Petitioner Different Spouse Rejection Condition: Moderate Reasons; "
                combPeopledf['[Calculated]FlagType'].values[i] = "Yellow"
                combPeopledf['[Calculated]FraudLikelihood'].values[i] = "Yes"
            elif q == 0:
                combPeopledf['[Calculated]FraudDescriptive'].values[i] += ""

In [600]:
combPeopledf['[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition'].unique()

array(['NA', '', 'Moderate Reasons', 'Minor Reasons', 'Major Reasons'],
      dtype=object)

In [608]:
combPeopledf.dtypes

ApplicantID                                                               int64
[I130]PeopleNamePetitioner                                               object
[I130A]PeopleNameBeneficiary                                             object
[I130]DOBPetitioner                                                      object
[I130]MailingStateFilingPetitioner                                       object
[I130A]CountryOfBirthBeneficiary                                         object
[I130A]GenderBeneficiary                                                 object
[I130]PassportExpiryBeneficiary                                          object
[I130]PreviousMaritalStatusPetitioner                                    object
[I130]PreviousMaritalStatusBeneficiary                                   object
[I130]PetitionerEthnicity                                                object
[I130]PetitionerRace                                                     object
[I130]PetitionerCitizenStatus                                            object
[I864]RegularIncome                                                       int64
[I864]SupplementalIncome                                                  int64
[I130]StayingTogetherStatus                                              object
[I130]CurrentMaritalStatus                                               object
[I864]FederalTaxFiled                                                    object
[I485-130]SameEmployer                                                   object
[I130]ImmigrationProceeding                                              object
[I485]CriminalityProvedConvicted                                         object
[I130]PreviousPetitionFiledPetitionerSameSpouse                          object
[I130]PreviousPetitionFiledDifferentSpouse                               object
[I130A]BeneficiaryInUS                                                   object
[I130-MarriageCertificate]SamePreparorNoterMinister                      object
[I130A]DOBBeneficiary                                                    object
[I130]GenderPetitioner                                                   object
[I130]PreviousLegallySeperatedCountryPetitioner                          object
[CALCULATED]AgeGapDays                                          timedelta64[ns]
[CALCULATED]AgePetitioner                                                 int64
[CALCULATED]AgeBeneficiary                                                int64
[CALCULATED]AgeGapYears                                                   int64
[I130]NumberOfMarriagesPetitioner                                         int64
[I130]NumberOfMarriagesBeneficiary                                        int64
[I485]CriminalityProvedConvictedType                                     object
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition                object
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition             object
[I130A]BeneficiaryEthnicity                                              object
[I864]NumberOfDependents                                                  int64
[CALCULATED]FederalPovertyLineValue                                       int64
[CALCULATED]TotalIncome                                                   int64
[I130]DateOfMarriage                                                     object
[I130]I94DateofEntry                                                     object
[I130]LastMarriageEndDatePetitioner                                      object
[I130]LastMarriageEndDateBeneficiary                                     object
[I864]FederalTaxFiledYears                                               object
[CALCULATED]LengthOfMarriage                                              int64
[CALCULATED]YearsSinceDateofEntry                                         int64
[CALCULATED]TotalYearsFromLastMarriagePetitioner                        float64
[CALCULATED]TotalYearsFromLastMarriageBeneficiary                       float64
[CALCULATED]DiffEntryDateAndMarriageDate                                float64
[Calculated]FlagType                                                     object
[Calculated]FraudLikelihood                                              object
[Calculated]FraudDescriptive                                             object
[Calculated]c1                                                           object
[Calculated]c2                                                           object
dtype: object

In [594]:
combPeopledf['[CALCULATED]DiffEntryDateAndMarriageDate'].unique()

array([1438., 1832., 2140., ..., 5416., 5488., 5277.])

In [583]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [1307]:
if __name__ == '__main__':
    main()

In [1308]:
combPeopledf

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[I130]LastMarriageEndDateBeneficiary,[I864]FederalTaxFiledYears,[CALCULATED]LengthOfMarriage,[CALCULATED]YearsSinceDateofEntry,[CALCULATED]TotalYearsFromLastMarriagePetitioner,[CALCULATED]TotalYearsFromLastMarriageBeneficiary,[CALCULATED]DiffEntryDateAndMarriageDate,[Calculated]FlagType,[Calculated]FraudLikelihood,[Calculated]FraudDescriptive
0,2000000,Jessica Smith,Teresa Aguilar,1972-07-05,Connecticut,Albania,M,2024-06-21,Not Hispanic or Latino,American Indian or Alaska Native,...,None,3 or 3+ years,6,11,NaN,NaN,1893.0,Green,No,
1,2000001,Cynthia Johnson,Hannah Hanson,1998-05-05,Utah,Gabon,M,2025-04-29,Not Hispanic or Latino,American Indian or Alaska Native,...,None,3 or 3+ years,6,13,NaN,NaN,2435.0,Green,No,
2,2000002,Micheal Bruce,Shirley Wright,1998-07-02,New Hampshire,Croatia,F,2023-12-19,Not Hispanic or Latino,White,...,None,3 or 3+ years,4,14,NaN,NaN,3720.0,Green,No,
3,2000003,Ann Riley,Justin Newman,1999-07-14,North Dakota,Iran,F,2028-11-03,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,None,3 or 3+ years,3,15,NaN,NaN,4545.0,Green,No,
4,2000004,Matthew Gonzalez,Mary David,1971-08-08,Wisconsin,Togo,F,2022-11-23,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,None,3 or 3+ years,6,16,NaN,NaN,3851.0,Yellow,Yes,Yellow Flag: Different State;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1349995,Casey Lawson,Cynthia Vance,1974-08-22,New Mexico,Tanzania,M,2029-12-26,Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,None,3 or 3+ years,0,8,0.81,NaN,3084.0,Red,Yes,Red Flag: Same State - Different Address; Red ...
49996,1349996,Kelly Richardson,Patricia Butler,1995-12-09,Iowa,Suriname,M,2027-04-14,Hispanic or Latino,American Indian or Alaska Native,...,None,Under 3 years,4,16,NaN,NaN,4094.0,Red,Yes,Red Flag: Same State - Different Address; Yell...
49997,1349997,Brandon Vargas,Carmen Cox,1968-02-23,Alabama,Paraguay,M,2031-04-10,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,None,3 or 3+ years,1,7,NaN,NaN,1978.0,Red,Yes,Red Flag: Same State - Different Address; Yell...
49998,1349998,Cassandra Avery,Amanda Moore,1988-11-29,North Carolina,Guinea,F,2028-09-24,Not Hispanic or Latino,American Indian or Alaska Native,...,2015-09-26,3 or 3+ years,4,11,NaN,1.81,2622.0,Red,Yes,Yellow Flag: Different State; Red Flag: Immigr...
49999,1349999,David Dickson,Erik Chapman,1969-01-28,South Carolina,Uzbekistan,M,2026-03-10,Not Hispanic or Latino,American Indian or Alaska Native,...,2016-09-03,3 or 3+ years,3,9,NaN,1.28,2049.0,Red,Yes,Yellow Flag: Age Gap in between 9 - 15 years; ...

In [1311]:
combPeopledf.to_csv('combPeopledfCheck750000.csv',index=False)

In [1309]:
combPeopledf['[Calculated]FlagType'].unique()

array(['Green', 'Yellow', 'Red'], dtype=object)

In [1310]:
combPeopledf['[Calculated]FraudLikelihood'].unique()

array(['No', 'Yes'], dtype=object)

In [581]:
combPeopledf['[Calculated]FraudDescriptive'].unique()

array(['', 'Yellow Flag: Marital Status - Not Married; ',
       'Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Immigration Proceeding; ',
       'Red Flag: Same State - Different Address; ',
       'Yellow Flag: Different State; ',
       'Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Criminal Record - Minor; ',
       'Yellow Flag: Different State; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Criminal Record - Minor; ',
       'Yellow Flag: Criminal Record - Minor; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Yellow Flag: Criminal Record - Minor; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Marital Status - Not Married; ',
       'Yellow Flag: Criminal Record - Minor; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Yellow Flag: Criminal Record - Minor; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Criminal Record - Minor; Yellow Flag: Marital Status - Not Married; ',
       'Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Criminal Record - Minor; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Immigration Proceeding; Red Flag: Same Employer; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; ',
       'Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Criminal Record - Minor; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Preparer/Noter/Minister; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Immigration Proceeding; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Red Flag: Criminal Record - Major; ',
       'Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Red Flag: Criminal Record - Major; ',
       'Yellow Flag: Different State; Yellow Flag: Criminal Record - Minor; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; ',
       'Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Criminal Record - Minor; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Criminal Record - Minor; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Criminal Record - Minor; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Red Flag: Criminal Record - Major; ',
       'Red Flag: Same Preparer/Noter/Minister; Red Flag: Criminal Record - Major; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Red Flag: Same Preparer/Noter/Minister; ',
       'Red Flag: Same Preparer/Noter/Minister; Red Flag: Criminal Record - Major; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Same Preparer/Noter/Minister; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Red Flag: Same Employer; Red Flag: Criminal Record - Major; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Red Flag: Criminal Record - Major; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; ',
       'Red Flag: Criminal Record - Major; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Criminal Record - Minor; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Criminal Record - Minor; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Yellow Flag: Criminal Record - Minor; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Criminal Record - Minor; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Yellow Flag: Marital Status - Not Married; ',
       'Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Criminal Record - Major; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Immigration Proceeding; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same Employer; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Red Flag: Same Employer; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Criminal Record - Minor; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Criminal Record - Major; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Preparer/Noter/Minister; ',
       'Yellow Flag: Different State; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same State - Different Address; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Criminal Record - Minor; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Criminal Record - Major; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Red Flag: Same Employer; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Red Flag: Criminal Record - Major; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; ',
       'Yellow Flag: Different State; Yellow Flag: Criminal Record - Minor; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; Yellow Flag: Marital Status - Not Married; ',
       'Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Red Flag: Criminal Record - Major; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Criminal Record - Minor; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Criminal Record - Major; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Red Flag: Criminal Record - Major; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same Preparer/Noter/Minister; Red Flag: Criminal Record - Major; ',
       'Red Flag: Criminal Record - Major; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; ',
       'Red Flag: Criminal Record - Major; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Preparer/Noter/Minister; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Immigration Proceeding; Red Flag: Same Employer; ',
       'Red Flag: Immigration Proceeding; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Immigration Proceeding; Red Flag: Same Preparer/Noter/Minister; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; Red Flag: Same Employer; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Yellow Flag: Different State; Red Flag: Immigration Proceeding; Yellow Flag: Criminal Record - Minor; Yellow Flag: Marital Status - Not Married; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Red Flag: Criminal Record - Major; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Beneficiary not in US; ',
       'Red Flag: Same Employer; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Yellow Flag: Criminal Record - Minor; Yellow Flag: Beneficiary not in US; ',
       'Yellow Flag: Criminal Record - Minor; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Beneficiary not in US; Yellow Flag: Age Gap in between 9 - 15 years; ',
       'Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; Red Flag: Age Gap greater than 15 years; ',
       'Yellow Flag: Different State; Red Flag: Same Employer; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Criminal Record - Minor; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; Red Flag: Age Gap greater than 15 years; ',
       'Red Flag: Same State - Different Address; Red Flag: Same Preparer/Noter/Minister; Yellow Flag: Marital Status - Not Married; Yellow Flag: Beneficiary not in US; ',

# 4. Machine Learning

## 4.1 Preprocessing Part 1: Creating Categorical Columns & Target Column

In [1316]:
dfCat = combPeopledf

In [1324]:
def AgeGapCategoricalFn(x):
    checkVal = x 
    if checkVal >= 15:
        a = "Age Gap >= 15 Years"
    elif checkVal >= 9 and checkVal < 15:
        a="Age Gap 9 - 15 Years"
    elif checkVal < 9:
        a="Age Gap < 9 Years"
    
    return a

In [1325]:
dfCat['[CALCULATED]AgeGapCategorical'] =  dfCat['[CALCULATED]AgeGapYears'].apply(lambda x: AgeGapCategoricalFn(x))

In [1326]:
dfCat[['[CALCULATED]AgeGapCategorical', '[CALCULATED]AgeGapYears']]

      [CALCULATED]AgeGapCategorical  [CALCULATED]AgeGapYears
0                 Age Gap < 9 Years                        8
1                 Age Gap < 9 Years                        7
2                 Age Gap < 9 Years                        4
3                 Age Gap < 9 Years                        0
4                 Age Gap < 9 Years                        5
...                             ...                      ...
49995           Age Gap >= 15 Years                       22
49996          Age Gap 9 - 15 Years                       11
49997           Age Gap >= 15 Years                       20
49998             Age Gap < 9 Years                        6
49999          Age Gap 9 - 15 Years                       14

[750000 rows x 2 columns]

In [1327]:
def IncomeCheckCategoricalFn(x,y):
    if x >= y:
        a = "Eligible"
    elif x < y:
        a = "Not-Eligible"
    
    return a

In [1328]:
dfCat['[CALCULATED]IncomeCheckCategorical'] = dfCat.apply(lambda x : IncomeCheckCategoricalFn(x['[CALCULATED]TotalIncome'], x['[CALCULATED]FederalPovertyLineValue']), axis=1)

In [1329]:
dfCat[['[CALCULATED]IncomeCheckCategorical', '[CALCULATED]TotalIncome', '[CALCULATED]FederalPovertyLineValue']]

,[CALCULATED]IncomeCheckCategorical,[CALCULATED]TotalIncome,[CALCULATED]FederalPovertyLineValue
0,Eligible,60808,27450
1,Eligible,41217,21775
2,Eligible,75583,21775
3,Eligible,71614,21775
4,Eligible,69864,27450
...,...,...,...
49995,Not-Eligible,28957,44475
49996,Eligible,53486,33125
49997,Eligible,91442,27450
49998,Eligible,44217,33125
49999,Eligible,106423,55825

In [1332]:
def FederalYearsFiledCheckCategoricalFn(x,y):
    if y >=23:
        if x == "3 or 3+ years":
            a="Green"
        elif x == "Under 3 years":
            a="Yellow"
        elif x == "NA":
            a="Red"
    elif y <23:
        if x == "3 or 3+ years":
            a="Green"
        elif x == "Under 3 years":
            a="Yellow"
        elif x == "NA":
            a="Yellow-Age Consideration"
    
    return a

In [1333]:
dfCat['[CALCULATED]FederalYearsFiledCheckCategorical'] = dfCat.apply(lambda x : FederalYearsFiledCheckCategoricalFn(x['[I864]FederalTaxFiledYears'], x['[CALCULATED]AgePetitioner']), axis=1)

In [1334]:
dfCat[['[CALCULATED]FederalYearsFiledCheckCategorical', '[I864]FederalTaxFiledYears', '[CALCULATED]AgePetitioner']]

,[CALCULATED]FederalYearsFiledCheckCategorical,[I864]FederalTaxFiledYears,[CALCULATED]AgePetitioner
0,Green,3 or 3+ years,49
1,Green,3 or 3+ years,23
2,Green,3 or 3+ years,23
3,Green,3 or 3+ years,22
4,Green,3 or 3+ years,50
...,...,...,...
49995,Green,3 or 3+ years,47
49996,Yellow,Under 3 years,25
49997,Green,3 or 3+ years,53
49998,Green,3 or 3+ years,32
49999,Green,3 or 3+ years,52

In [1335]:
dfCat['[CALCULATED]FederalYearsFiledCheckCategorical'].unique()

array(['Green', 'Yellow', 'Red', 'Yellow-Age Consideration'], dtype=object)

In [1351]:
def TotalYearsFromLastMarriageCategoricalFn(x):
    if x >= 2:
        a="2 or More Years"
    elif x < 2:
        a="Less than 2 Years"
    else:
        a="Green"
    
    return a

In [1352]:
dfCat['[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical'] =  dfCat['[CALCULATED]TotalYearsFromLastMarriagePetitioner'].apply(lambda x: TotalYearsFromLastMarriageCategoricalFn(x))

In [1353]:
dfCat['[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical'] =  dfCat['[CALCULATED]TotalYearsFromLastMarriageBeneficiary'].apply(lambda x: TotalYearsFromLastMarriageCategoricalFn(x))

In [1354]:
dfCat[['[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitioner']]

,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitioner
0,Green,NaN
1,Green,NaN
2,Green,NaN
3,Green,NaN
4,Green,NaN
...,...,...
49995,Less than 2 Years,0.81
49996,Green,NaN
49997,Green,NaN
49998,Green,NaN
49999,Green,NaN

In [1355]:
dfCat[['[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiary']]

,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiary
0,Green,NaN
1,Green,NaN
2,Green,NaN
3,Green,NaN
4,Green,NaN
...,...,...
49995,Green,NaN
49996,Green,NaN
49997,Green,NaN
49998,Less than 2 Years,1.81
49999,Less than 2 Years,1.28

In [1356]:
dfCat['[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical'].unique()

array(['Green', '2 or More Years', 'Less than 2 Years'], dtype=object)

In [1357]:
dfCat['[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical'].unique()

array(['Green', '2 or More Years', 'Less than 2 Years'], dtype=object)

In [1343]:
def LengthOfMarriageCategoricalFn(x,y,z):
    if y <=22 or z <=22:
        if x >=2:
            a="Green"
        elif x <=2:
            a="Yellow-Age Consideration"
    elif y > 22 and z > 22:
        if x >=3:
            a="Green"
        elif x >=2 and x < 3:
            a="Yellow"
        elif x < 2:
            a="Red"
    
    return a

In [1344]:
dfCat['[CALCULATED]LengthOfMarriageCategorical'] = dfCat.apply(lambda x : LengthOfMarriageCategoricalFn(x['[CALCULATED]LengthOfMarriage'], x['[CALCULATED]AgeBeneficiary'], x['[CALCULATED]AgePetitioner']), axis=1)

In [1345]:
dfCat[['[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]LengthOfMarriage','[CALCULATED]AgeBeneficiary','[CALCULATED]AgePetitioner']]

,[CALCULATED]LengthOfMarriageCategorical,[CALCULATED]LengthOfMarriage,[CALCULATED]AgeBeneficiary,[CALCULATED]AgePetitioner
0,Green,6,57,49
1,Green,6,30,23
2,Green,4,27,23
3,Green,3,22,22
4,Green,6,45,50
...,...,...,...,...
49995,Red,0,25,47
49996,Green,4,36,25
49997,Red,1,33,53
49998,Green,4,26,32
49999,Green,3,38,52

In [1346]:
dfCat['[CALCULATED]LengthOfMarriageCategorical'].unique()

array(['Green', 'Yellow', 'Yellow-Age Consideration', 'Red'], dtype=object)

In [1347]:
def DiffEntryDateAndMarriageDateCategoricalFn(x):
    if x <= 180:
        a="Difference < 180 Days"
    elif x > 180 and x <= 730:
        a="Difference between 180 - 730 Days"
    elif x >= 731:
        a="Difference >= 731 Days"
    
    return a

In [1348]:
dfCat['[CALCULATED]DiffEntryDateAndMarriageDateCategorical'] =  dfCat['[CALCULATED]DiffEntryDateAndMarriageDate'].apply(lambda x: DiffEntryDateAndMarriageDateCategoricalFn(x))

In [1349]:
dfCat[['[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[CALCULATED]DiffEntryDateAndMarriageDate']]

,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,[CALCULATED]DiffEntryDateAndMarriageDate
0,Difference >= 731 Days,1893.0
1,Difference >= 731 Days,2435.0
2,Difference >= 731 Days,3720.0
3,Difference >= 731 Days,4545.0
4,Difference >= 731 Days,3851.0
...,...,...
49995,Difference >= 731 Days,3084.0
49996,Difference >= 731 Days,4094.0
49997,Difference >= 731 Days,1978.0
49998,Difference >= 731 Days,2622.0
49999,Difference >= 731 Days,2049.0

In [1350]:
dfCat['[CALCULATED]DiffEntryDateAndMarriageDateCategorical'].unique()

array(['Difference >= 731 Days', 'Difference between 180 - 730 Days',
       'Difference < 180 Days'], dtype=object)

In [1358]:
dfCat.to_csv('dfCat.csv',index=False)

In [1359]:
dfCat['Target'] = dfCat['[Calculated]FraudLikelihood'].apply(lambda x: 1 if x == 'Yes' else 0 )

In [1360]:
dfCat[['Target', '[Calculated]FraudLikelihood']]

       Target [Calculated]FraudLikelihood
0           0                          No
1           0                          No
2           0                          No
3           0                          No
4           1                         Yes
...       ...                         ...
49995       1                         Yes
49996       1                         Yes
49997       1                         Yes
49998       1                         Yes
49999       1                         Yes

[750000 rows x 2 columns]

## 4.2 Preprocessing Part 2: Data Shuffling

In [1361]:
primeDF = dfCat.sample(frac = 1) # First Shuffle
print(primeDF)

       ApplicantID [I130]PeopleNamePetitioner [I130A]PeopleNameBeneficiary  \
33890      2233890                Kyle Nguyen             Jacqueline Welch
46109      2746109                Dale Miller               Lauren Jackson
27186      2527186              Lisa Long DVM               Nancy Thompson
15455      2815455               James Flores               Michael Newton
48681      2348681               Jason Murphy               Lawrence Davis
...            ...                        ...                          ...
43571      2243571              Mallory Brown                 John Jenkins
11664      3011664            Dr. Troy Walker                 Felicia Hunt
14261      2014261               Barry Jordan               Cindy Anderson
31634      1131634              Andrea Warren               Christian Wood
41571      1241571            Dustin Robinson               Melissa Taylor

      [I130]DOBPetitioner [I130]MailingStateFilingPetitioner  \
33890          1997-09-18                               Iowa
46109          1972-08-08                             Kansas
27186          1991-11-14                      Massachusetts
15455          1998-06-30                         New Mexico
48681          2000-10-23                            Vermont
...                   ...                                ...
43571          1992-12-24                            Wyoming
11664          1987-03-25                             Alaska
14261          1983-05-29                            Georgia
31634          1962-09-06                           Missouri
41571          1984-07-10                       Rhode Island

      [I130A]CountryOfBirthBeneficiary [I130A]GenderBeneficiary  \
33890                             Mali                        F
46109                             Mali                        M
27186                      Ivory Coast                        M
15455                          Romania                        F
48681                             Iran                        M
...                                ...                      ...
43571                            Libya                        F
11664                           Kuwait                        F
14261                       Montenegro                        M
31634                          Estonia                        F
41571                             Cuba                        F

      [I130]PassportExpiryBeneficiary [I130]PetitionerEthnicity  \
33890                      2026-10-22        Hispanic or Latino
46109                      2030-06-10    Not Hispanic or Latino
27186                      2031-03-13    Not Hispanic or Latino
15455                      2027-10-31             Not Specified
48681                      2027-05-08             Not Specified
...                               ...                       ...
43571                      2029-02-09        Hispanic or Latino
11664                      2026-04-20    Not Hispanic or Latino
14261                      2027-12-26    Not Hispanic or Latino
31634                      2025-12-16        Hispanic or Latino
41571                      2029-06-28    Not Hispanic or Latino

                   [I130]PetitionerRace  ... [Calculated]FraudLikelihood  \
33890                             Asian  ...                         Yes
46109        Black or African Ammerican  ...                          No
27186  American Indian or Alaska Native  ...                          No
15455                             White  ...                          No
48681  American Indian or Alaska Native  ...                         Yes
...                                 ...  ...                         ...
43571                             Asian  ...                          No
11664  American Indian or Alaska Native  ...                          No
14261                             White  ...                         Yes
31634        Black or African Ammerican  ...                         Yes
41571        Black or African Ammerican  ...                         Yes

                            [Calculated]FraudDescriptive  \
33890  Yellow Flag: Length of Marriage in between 2-3...
46109
27186
15455
48681  Yellow Flag: Marital Status - Not Married; Yel...
...                                                  ...
43571
11664
14261  Red Flag: Total Income less than Federal Pover...
31634  Red Flag: Same State - Different Address; Red ...
41571  Yellow Flag: Different State; Red Flag: Immigr...

       [CALCULATED]AgeGapCategorical [CALCULATED]IncomeCheckCategorical  \
33890              Age Gap < 9 Years                           Eligible
46109              Age Gap < 9 Years                           Eligible
27186              Age Gap < 9 Years                           Eligible
15455              Age Gap < 9 Years                           Eligible
48681              Age Gap < 9 Years                           Eligible
...                              ...                                ...
43571              Age Gap < 9 Years                           Eligible
11664              Age Gap < 9 Years                           Eligible
14261              Age Gap < 9 Years                       Not-Eligible
31634            Age Gap >= 15 Years                           Eligible
41571              Age Gap < 9 Years                           Eligible

      [CALCULATED]FederalYearsFiledCheckCategorical  \
33890                                         Green
46109                                         Green
27186                                         Green
15455                                         Green
48681                                        Yellow
...                                             ...
43571                                         Green
11664                                         Green
14261                                         Green
31634                                         Green
41571                                         Green

      [CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical  \
33890                                              Green
46109                                              Green
27186                                              Green
15455                                              Green
48681                                              Green
...                                                  ...
43571                                              Green
11664                                              Green
14261                                              Green
31634                                  Less than 2 Years
41571                                              Green

      [CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical  \
33890                                              Green
46109                                              Green
27186                                              Green
15455                                              Green
48681                                              Green
...                                                  ...
43571                                              Green
11664                                              Green
14261                                              Green
31634                                  Less than 2 Years
41571                                              Green

      [CALCULATED]LengthOfMarriageCategorical  \
33890                                  Yellow
46109                                   Green
27186                                   Green
15455                                   Green
48681                                   Green
...                                       ...
43571                                   Green
11664                                   Green
14261                                   Green
31634                                   Green
41571                                     Red

      [CALCULATED]DiffEntryDateAndMarriageDateCategorical Target
33890                             Difference >= 731 Days       1
46109                             Difference >= 731 Days       0
27186                             Difference >= 731 Days       0
15455                             Difference >= 731 Days       0
48681                             Difference >= 731 Days       1
...                                                  ...     ...
43571                             Difference >= 731 Days       0
11664                             Difference >= 731 Days       0
14261                             Difference >= 731 Days       1
31634                             Difference >= 731 Days       1
41571                             Difference >= 731 Days       1

[750000 rows x 62 columns]

In [1362]:
primeDF = primeDF.sample(frac = 1) # Second Shuffle
print(primeDF)

       ApplicantID [I130]PeopleNamePetitioner [I130A]PeopleNameBeneficiary  \
22993      1322993            Jennifer Torres                 Lori Herrera
17799      1117799               Daniel Lopez                Thomas Bowers
47640      2847640            Laurie Copeland                 Andrew Lopez
7712       2407712                Sarah Moore              Thomas Morrison
9994       2109994                 Lisa Reyes             Jordan Rodriguez
...            ...                        ...                          ...
27211      2727211                Tanya Munoz                  Laurie Reid
40667      2240667             Jessica Foster             Vanessa Thompson
25383      1025383             Heather Wilcox               Patrick Garcia
49057      2649057                 Chad Smith                 Stacy George
15595      1115595            Matthew Parsons                 Kelly Morgan

      [I130]DOBPetitioner [I130]MailingStateFilingPetitioner  \
22993          1961-11-11                     North Carolina
17799          1990-07-06                        Mississippi
47640          1967-12-08                       South Dakota
7712           1995-09-02                         New Jersey
9994           1974-07-23                       Pennsylvania
...                   ...                                ...
27211          1970-12-10                            Arizona
40667          1979-07-27                            Wyoming
25383          1988-09-03                           New York
49057          1997-11-09                           Maryland
15595          1975-02-21                            Montana

      [I130A]CountryOfBirthBeneficiary [I130A]GenderBeneficiary  \
22993                      South Sudan                        F
17799                     South Africa                        F
47640                         Paraguay                        M
7712                             Japan                        F
9994                Russian Federation                        F
...                                ...                      ...
27211                          Ukraine                        F
40667                 St Kitts & Nevis                        F
25383                           Mexico                        M
49057                        Indonesia                        F
15595                       Costa Rica                        M

      [I130]PassportExpiryBeneficiary [I130]PetitionerEthnicity  \
22993                      2023-04-01    Not Hispanic or Latino
17799                      2029-05-14    Not Hispanic or Latino
47640                      2031-10-11        Hispanic or Latino
7712                       2027-04-15    Not Hispanic or Latino
9994                       2024-01-19    Not Hispanic or Latino
...                               ...                       ...
27211                      2026-09-16        Hispanic or Latino
40667                      2025-09-02    Not Hispanic or Latino
25383                      2025-07-15        Hispanic or Latino
49057                      2030-05-28    Not Hispanic or Latino
15595                      2028-05-13    Not Hispanic or Latino

                            [I130]PetitionerRace  ...  \
22993           American Indian or Alaska Native  ...
17799                                      Asian  ...
47640           American Indian or Alaska Native  ...
7712                                       White  ...
9994   Native Hawaiian or Other Pacific Islander  ...
...                                          ...  ...
27211                 Black or African Ammerican  ...
40667                 Black or African Ammerican  ...
25383           American Indian or Alaska Native  ...
49057                                      Asian  ...
15595                                      White  ...

      [Calculated]FraudLikelihood  \
22993                         Yes
17799                         Yes
47640                          No
7712                           No
9994                           No
...                           ...
27211                         Yes
40667                          No
25383                         Yes
49057                          No
15595                         Yes

                            [Calculated]FraudDescriptive  \
22993  Red Flag: Same State - Different Address; Red ...
17799  Yellow Flag: Criminal Record - Minor; Red Flag...
47640
7712
9994
...                                                  ...
27211               Yellow Flag: Beneficiary not in US;
40667
25383  Red Flag: Same Employer; Red Flag: Beneficiary...
49057
15595  Red Flag: Same State - Different Address; Yell...

       [CALCULATED]AgeGapCategorical [CALCULATED]IncomeCheckCategorical  \
22993            Age Gap >= 15 Years                           Eligible
17799            Age Gap >= 15 Years                           Eligible
47640              Age Gap < 9 Years                           Eligible
7712               Age Gap < 9 Years                           Eligible
9994               Age Gap < 9 Years                           Eligible
...                              ...                                ...
27211              Age Gap < 9 Years                           Eligible
40667              Age Gap < 9 Years                           Eligible
25383              Age Gap < 9 Years                           Eligible
49057              Age Gap < 9 Years                           Eligible
15595           Age Gap 9 - 15 Years                           Eligible

      [CALCULATED]FederalYearsFiledCheckCategorical  \
22993                                           Red
17799                                         Green
47640                                         Green
7712                                          Green
9994                                          Green
...                                             ...
27211                                         Green
40667                                         Green
25383                                         Green
49057                                         Green
15595                                           Red

      [CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical  \
22993                                              Green
17799                                  Less than 2 Years
47640                                              Green
7712                                               Green
9994                                               Green
...                                                  ...
27211                                              Green
40667                                    2 or More Years
25383                                              Green
49057                                              Green
15595                                  Less than 2 Years

      [CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical  \
22993                                  Less than 2 Years
17799                                              Green
47640                                              Green
7712                                               Green
9994                                               Green
...                                                  ...
27211                                              Green
40667                                              Green
25383                                  Less than 2 Years
49057                                              Green
15595                                              Green

      [CALCULATED]LengthOfMarriageCategorical  \
22993                                   Green
17799                                     Red
47640                                   Green
7712                                    Green
9994                                    Green
...                                       ...
27211                                   Green
40667                                   Green
25383                                     Red
49057                                   Green
15595                                   Green

      [CALCULATED]DiffEntryDateAndMarriageDateCategorical Target
22993                             Difference >= 731 Days       1
17799                             Difference >= 731 Days       1
47640                             Difference >= 731 Days       0
7712                              Difference >= 731 Days       0
9994                              Difference >= 731 Days       0
...                                                  ...     ...
27211                             Difference >= 731 Days       1
40667                             Difference >= 731 Days       0
25383                             Difference >= 731 Days       1
49057                             Difference >= 731 Days       0
15595                             Difference >= 731 Days       1

[750000 rows x 62 columns]

## 4.3 Preprocessing Part 3: Continue Optimizing Columns

In [1398]:
primeDF['[I485]CriminalityProvedConvictedTypeN'].unique()

array(['Green', 'Minor Reasons', 'Major Reasons'], dtype=object)

In [1374]:
def PreviousFiledPetitionerRejectionConditionFn(x):
    if x=="Minor Reasons" or x == "NA":
        a = "Green"
    else:
        a = x
    
    return a

In [1375]:
primeDF['[I130]PreviousFiledPetitionerSameSpouseRejectionCondition'] =  primeDF['[I130]PreviousFiledPetitionerSameSpouseRejectionCondition'].apply(lambda x: PreviousFiledPetitionerRejectionConditionFn(x))

In [1378]:
primeDF['[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition'] =  primeDF['[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition'].apply(lambda x: PreviousFiledPetitionerRejectionConditionFn(x))

In [1392]:
def CriminalityProvedConvictedTypeFn(x):
    if x == "NA":
        a = "Green"
    else:
        a = x
        
    return a

In [1393]:
primeDF['[I485]CriminalityProvedConvictedTypeN'] =  primeDF['[I485]CriminalityProvedConvictedType'].apply(lambda x: CriminalityProvedConvictedTypeFn(x))

In [1395]:
primeDF[['[I485]CriminalityProvedConvictedTypeN', '[I485]CriminalityProvedConvictedType']]

,[I485]CriminalityProvedConvictedTypeN,[I485]CriminalityProvedConvictedType
22993,Green,NA
17799,Minor Reasons,Minor Reasons
47640,Green,NA
7712,Green,NA
9994,Green,NA
...,...,...
27211,Green,NA
40667,Green,NA
25383,Green,NA
49057,Green,NA
15595,Green,NA

In [1401]:
primeDF['[I485]CriminalityProvedConvictedTypeN'].value_counts()

Green            714494
Minor Reasons     26540
Major Reasons      8966
Name: [I485]CriminalityProvedConvictedTypeN, dtype: int64

In [1390]:
label = primeDF['Target']

In [1399]:
primeDF.to_csv('primeDF.csv',index=False)

## 4.3 Machine Learning Modeling

### 4.3.1 Support Vector Machine

In [1363]:
from sklearn import preprocessing
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.model_selection import train_test_split
import seaborn as sns
#sns.set(style="white")
#sns.set(style="whitegrid", color_codes=True)

In [1402]:
pd.set_option('display.max_rows', 70)
primeDF.dtypes

ApplicantID                                                               int64
[I130]PeopleNamePetitioner                                               object
[I130A]PeopleNameBeneficiary                                             object
[I130]DOBPetitioner                                                      object
[I130]MailingStateFilingPetitioner                                       object
[I130A]CountryOfBirthBeneficiary                                         object
[I130A]GenderBeneficiary                                                 object
[I130]PassportExpiryBeneficiary                                          object
[I130]PetitionerEthnicity                                                object
[I130]PetitionerRace                                                     object
[I130]PetitionerCitizenStatus                                            object
[I864]RegularIncome                                                       int64
[I864]SupplementalIncome                                                  int64
[I130]StayingTogetherStatus                                              object
[I130]CurrentMaritalStatus                                               object
[I864]FederalTaxFiled                                                    object
[I485-130]SameEmployer                                                   object
[I130]ImmigrationProceeding                                              object
[I485]CriminalityProvedConvicted                                         object
[I130]PreviousPetitionFiledPetitionerSameSpouse                          object
[I130]PreviousPetitionFiledDifferentSpouse                               object
[I130A]BeneficiaryInUS                                                   object
[I130-MarriageCertificate]SamePreparorNoterMinister                      object
[I130A]DOBBeneficiary                                                    object
[I130]GenderPetitioner                                                   object
[CALCULATED]AgeGapDays                                          timedelta64[ns]
[CALCULATED]AgePetitioner                                                 int64
[CALCULATED]AgeBeneficiary                                                int64
[CALCULATED]AgeGapYears                                                   int64
[I130]PreviousMaritalStatusPetitioner                                    object
[I130]PreviousMaritalStatusBeneficiary                                   object
[I130]PreviousLegallySeperatedCountryPetitioner                          object
[I130]NumberOfMarriagesPetitioner                                         int64
[I130]NumberOfMarriagesBeneficiary                                        int64
[I485]CriminalityProvedConvictedType                                     object
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition                object
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition             object
[I130A]BeneficiaryEthnicity                                              object
[I864]NumberOfDependents                                                  int64
[CALCULATED]FederalPovertyLineValue                                       int64
[CALCULATED]TotalIncome                                                   int64
[I130]DateOfMarriage                                                     object
[I130]I94DateofEntry                                                     object
[I130]LastMarriageEndDatePetitioner                                      object
[I130]LastMarriageEndDateBeneficiary                                     object
[I864]FederalTaxFiledYears                                               object
[CALCULATED]LengthOfMarriage                                              int64
[CALCULATED]YearsSinceDateofEntry                                         int64
[CALCULATED]TotalYearsFromLastMarriagePetitioner                        float64
[CALCULATED]TotalYearsFromLastMarriageBeneficiary                       float64
[CALCULATED]DiffEntryDateAndMarriageDate                                float64
[Calculated]FlagType                                                     object
[Calculated]FraudLikelihood                                              object
[Calculated]FraudDescriptive                                             object
[CALCULATED]AgeGapCategorical                                            object
[CALCULATED]IncomeCheckCategorical                                       object
[CALCULATED]FederalYearsFiledCheckCategorical                            object
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical              object
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical             object
[CALCULATED]LengthOfMarriageCategorical                                  object
[CALCULATED]DiffEntryDateAndMarriageDateCategorical                      object
Target                                                                    int64
[I485]CriminalityProvedConvictedTypeN                                    object
dtype: object

In [1416]:
primeDfSubset=primeDF[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN','Target' ]]

In [1417]:
primeDfSubset.dtypes

[I130]StayingTogetherStatus                                      object
[I130]CurrentMaritalStatus                                       object
[I485-130]SameEmployer                                           object
[I130]ImmigrationProceeding                                      object
[I130A]BeneficiaryInUS                                           object
[I130-MarriageCertificate]SamePreparorNoterMinister              object
[CALCULATED]AgeGapYears                                           int64
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition        object
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition     object
[CALCULATED]LengthOfMarriage                                      int64
[CALCULATED]DiffEntryDateAndMarriageDate                        float64
[CALCULATED]AgeGapCategorical                                    object
[CALCULATED]IncomeCheckCategorical                               object
[CALCULATED]FederalYearsFiledCheckCategorical                    object
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical      object
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical     object
[CALCULATED]LengthOfMarriageCategorical                          object
[CALCULATED]DiffEntryDateAndMarriageDateCategorical              object
[I485]CriminalityProvedConvictedTypeN                            object
Target                                                            int64
dtype: object

In [1419]:
primeDfSubsetSVM = primeDfSubset

In [1429]:
primeDfSubsetSVMS = primeDfSubsetSVM.sample(frac = 0.1)

In [1491]:
primeDfSubsetSVMSTrue = primeDfSubsetSVM[primeDfSubsetSVM['Target'] < 1].sample(n = 50000)

In [1492]:
primeDfSubsetSVMSTrue['Target'].value_counts()

0    50000
Name: Target, dtype: int64

In [1493]:
primeDfSubsetSVMSFalse = primeDfSubsetSVM[primeDfSubsetSVM['Target'] > 0].sample(n = 25000)

In [1494]:
primeDfSubsetSVMSFalse['Target'].value_counts()

1    25000
Name: Target, dtype: int64

In [1495]:
primeDfSubsetSVMSTF = [primeDfSubsetSVMSTrue, primeDfSubsetSVMSFalse]

In [1496]:
primeDfSubsetSVMSTF = pd.concat(primeDfSubsetSVMSTF)

In [1497]:
primeDfSubsetSVMSTF['Target'].value_counts()

0    50000
1    25000
Name: Target, dtype: int64

In [1432]:
primeDfSubsetSVMS['Target'].value_counts()

0    43240
1    31760
Name: Target, dtype: int64

In [1498]:
primeDfSubsetSVMSTFRandom = primeDfSubsetSVMSTF.sample(frac = 1)

In [1421]:
from sklearn.preprocessing import OneHotEncoder

In [1460]:
xEncode = primeDfSubsetSVMS[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN' ]].copy(True)

In [1434]:
xEncode.dtypes

[I130]StayingTogetherStatus                                      object
[I130]CurrentMaritalStatus                                       object
[I485-130]SameEmployer                                           object
[I130]ImmigrationProceeding                                      object
[I130A]BeneficiaryInUS                                           object
[I130-MarriageCertificate]SamePreparorNoterMinister              object
[CALCULATED]AgeGapYears                                           int64
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition        object
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition     object
[CALCULATED]LengthOfMarriage                                      int64
[CALCULATED]DiffEntryDateAndMarriageDate                        float64
[CALCULATED]AgeGapCategorical                                    object
[CALCULATED]IncomeCheckCategorical                               object
[CALCULATED]FederalYearsFiledCheckCategorical                    object
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical      object
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical     object
[CALCULATED]LengthOfMarriageCategorical                          object
[CALCULATED]DiffEntryDateAndMarriageDateCategorical              object
[I485]CriminalityProvedConvictedTypeN                            object
dtype: object

In [1461]:
xEncode = pd.get_dummies(xEncode, columns= ['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN'])

In [1462]:
xEncode.head(20)

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,...,[CALCULATED]LengthOfMarriageCategorical_Green,[CALCULATED]LengthOfMarriageCategorical_Red,[CALCULATED]LengthOfMarriageCategorical_Yellow,[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
47375,7,5,2778.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
3027,7,5,1933.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
30163,3,5,4824.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
20489,2,5,1303.0,0,1,0,0,1,1,0,...,1,0,0,0,0,1,0,1,0,0
46210,7,5,1830.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
31991,2,5,3365.0,0,0,1,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
10351,8,4,2928.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
14185,18,3,217.0,0,1,0,1,0,1,0,...,1,0,0,0,0,0,1,1,0,0
34439,5,5,4296.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
15751,15,2,2979.0,1,0,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
5483,7,5,1021.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
13754,7,4,1582.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
1210,2,3,4531.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
46962,6,4,2779.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
15341,2,3,1240.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
43501,1,6,3745.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
3436,6,5,2072.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
4175,18,1,4103.0,0,0,1,1,0,1,0,...,0,1,0,0,0,1,0,1,0,0
2733,3,3,308.0,0,0,1,1,0,1,0,...,1,0,0,0,0,0,1,1,0,0
17996,1,3,4839.0,0,0,1,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0

In [1441]:
xEncode.to_csv('xEncode10Perc.csv',index=False)

In [1446]:
xEncode

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,...,[CALCULATED]LengthOfMarriageCategorical_Green,[CALCULATED]LengthOfMarriageCategorical_Red,[CALCULATED]LengthOfMarriageCategorical_Yellow,[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
47375,7,5,2778.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
3027,7,5,1933.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
30163,3,5,4824.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
20489,2,5,1303.0,0,1,0,0,1,1,0,...,1,0,0,0,0,1,0,1,0,0
46210,7,5,1830.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29374,2,6,4098.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
12881,4,5,4445.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
24885,7,6,2214.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
34699,5,5,3100.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
45128,1,5,3907.0,1,0,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0

In [1463]:
xEncode.corr().style.background_gradient(cmap="GnBu")

In [1448]:
t = xEncode.corr().abs()

In [1449]:
upper = t.where(np.triu(np.ones(t.shape), k=1).astype(np.bool))

<ipython-input-1449-b392a26fe95d>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  upper = t.where(np.triu(np.ones(t.shape), k=1).astype(np.bool))

In [1456]:
to_drop = [column for column in upper.columns if any(upper[column] > 0.80)]

In [1464]:
xEncodeLowCorr = xEncode.drop(xEncode[to_drop], axis=1)

In [1458]:
xEncodeLowCorr.dtypes

[CALCULATED]AgeGapYears                                                             int64
[CALCULATED]LengthOfMarriage                                                        int64
[CALCULATED]DiffEntryDateAndMarriageDate                                          float64
[I130]StayingTogetherStatus_Different States                                        uint8
[I130]StayingTogetherStatus_Same House                                              uint8
[I130]StayingTogetherStatus_Same State - Different Address                          uint8
[I130]CurrentMaritalStatus_Married                                                  uint8
[I485-130]SameEmployer_No                                                           uint8
[I130]ImmigrationProceeding_No                                                      uint8
[I130A]BeneficiaryInUS_No                                                           uint8
[I130-MarriageCertificate]SamePreparorNoterMinister_No                              uint8
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition_Green                     uint8
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition_Major Reasons             uint8
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition_Green                  uint8
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition_Major Reasons          uint8
[CALCULATED]AgeGapCategorical_Age Gap 9 - 15 Years                                  uint8
[CALCULATED]IncomeCheckCategorical_Eligible                                         uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Green                                 uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Red                                   uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Yellow                                uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Yellow-Age Consideration              uint8
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_2 or More Years         uint8
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Green                   uint8
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Less than 2 Years       uint8
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_2 or More Years        uint8
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Green                  uint8
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Less than 2 Years      uint8
[CALCULATED]LengthOfMarriageCategorical_Green                                       uint8
[CALCULATED]LengthOfMarriageCategorical_Red                                         uint8
[CALCULATED]LengthOfMarriageCategorical_Yellow                                      uint8
[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration                    uint8
[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days           uint8
[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days          uint8
[I485]CriminalityProvedConvictedTypeN_Green                                         uint8
[I485]CriminalityProvedConvictedTypeN_Major Reasons                                 uint8
dtype: object

In [1455]:
xEncode.dtypes

[CALCULATED]AgeGapYears                                                                    int64
[CALCULATED]LengthOfMarriage                                                               int64
[CALCULATED]DiffEntryDateAndMarriageDate                                                 float64
[I130]StayingTogetherStatus_Different States                                               uint8
[I130]StayingTogetherStatus_Same House                                                     uint8
[I130]StayingTogetherStatus_Same State - Different Address                                 uint8
[I130]CurrentMaritalStatus_Married                                                         uint8
[I130]CurrentMaritalStatus_Separated                                                       uint8
[I485-130]SameEmployer_No                                                                  uint8
[I485-130]SameEmployer_Yes                                                                 uint8
[I130]ImmigrationProceeding_No                                                             uint8
[I130]ImmigrationProceeding_Yes                                                            uint8
[I130A]BeneficiaryInUS_No                                                                  uint8
[I130A]BeneficiaryInUS_Yes                                                                 uint8
[I130-MarriageCertificate]SamePreparorNoterMinister_No                                     uint8
[I130-MarriageCertificate]SamePreparorNoterMinister_Yes                                    uint8
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition_Green                            uint8
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition_Major Reasons                    uint8
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition_Moderate Reasons                 uint8
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition_Green                         uint8
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition_Major Reasons                 uint8
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition_Moderate Reasons              uint8
[CALCULATED]AgeGapCategorical_Age Gap 9 - 15 Years                                         uint8
[CALCULATED]AgeGapCategorical_Age Gap < 9 Years                                            uint8
[CALCULATED]AgeGapCategorical_Age Gap >= 15 Years                                          uint8
[CALCULATED]IncomeCheckCategorical_Eligible                                                uint8
[CALCULATED]IncomeCheckCategorical_Not-Eligible                                            uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Green                                        uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Red                                          uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Yellow                                       uint8
[CALCULATED]FederalYearsFiledCheckCategorical_Yellow-Age Consideration                     uint8
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_2 or More Years                uint8
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Green                          uint8
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Less than 2 Years              uint8
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_2 or More Years               uint8
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Green                         uint8
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Less than 2 Years             uint8
[CALCULATED]LengthOfMarriageCategorical_Green                                              uint8
[CALCULATED]LengthOfMarriageCategorical_Red                                                uint8
[CALCULATED]LengthOfMarriageCategorical_Yellow                                             uint8
[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration                           uint8
[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days                  uint8
[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days                 uint8
[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days      uint8
[I485]CriminalityProvedConvictedTypeN_Green                                                uint8
[I485]CriminalityProvedConvictedTypeN_Major Reasons                                        uint8
[I485]CriminalityProvedConvictedTypeN_Minor Reasons                                        uint8
dtype: object

In [1459]:
xEncodeLowCorr

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I485-130]SameEmployer_No,[I130]ImmigrationProceeding_No,[I130A]BeneficiaryInUS_No,...,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Green,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Less than 2 Years,[CALCULATED]LengthOfMarriageCategorical_Green,[CALCULATED]LengthOfMarriageCategorical_Red,[CALCULATED]LengthOfMarriageCategorical_Yellow,[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons
47375,7,5,2778.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
3027,7,5,1933.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
30163,3,5,4824.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
20489,2,5,1303.0,0,1,0,0,1,1,0,...,1,0,1,0,0,0,0,1,1,0
46210,7,5,1830.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29374,2,6,4098.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
12881,4,5,4445.0,0,1,0,1,1,1,1,...,1,0,1,0,0,0,0,1,1,0
24885,7,6,2214.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
34699,5,5,3100.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
45128,1,5,3907.0,1,0,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0

In [1454]:
xEncode

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,...,[CALCULATED]LengthOfMarriageCategorical_Green,[CALCULATED]LengthOfMarriageCategorical_Red,[CALCULATED]LengthOfMarriageCategorical_Yellow,[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
47375,7,5,2778.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
3027,7,5,1933.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
30163,3,5,4824.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
20489,2,5,1303.0,0,1,0,0,1,1,0,...,1,0,0,0,0,1,0,1,0,0
46210,7,5,1830.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29374,2,6,4098.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
12881,4,5,4445.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
24885,7,6,2214.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
34699,5,5,3100.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
45128,1,5,3907.0,1,0,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0

In [1465]:
y = primeDfSubsetSVMS['Target']

In [1467]:
X1 = xEncode.drop(['[CALCULATED]AgeGapYears','[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate'], axis=1)

In [1468]:
X2 = xEncode.drop(['[CALCULATED]AgeGapCategorical_Age Gap 9 - 15 Years','[CALCULATED]AgeGapCategorical_Age Gap < 9 Years','[CALCULATED]AgeGapCategorical_Age Gap >= 15 Years', '[CALCULATED]LengthOfMarriageCategorical_Green','[CALCULATED]LengthOfMarriageCategorical_Red','[CALCULATED]LengthOfMarriageCategorical_Yellow','[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration','[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days','[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days','[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days'], axis=1)

In [1469]:
X3 = xEncodeLowCorr

In [1470]:
X1

,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,[I130]ImmigrationProceeding_No,[I130]ImmigrationProceeding_Yes,[I130A]BeneficiaryInUS_No,...,[CALCULATED]LengthOfMarriageCategorical_Green,[CALCULATED]LengthOfMarriageCategorical_Red,[CALCULATED]LengthOfMarriageCategorical_Yellow,[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
47375,0,1,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
3027,0,1,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
30163,0,1,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
20489,0,1,0,0,1,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
46210,0,1,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29374,0,1,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
12881,0,1,0,1,0,1,0,1,0,1,...,1,0,0,0,0,1,0,1,0,0
24885,0,1,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
34699,0,1,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0
45128,1,0,0,1,0,1,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0

In [1471]:
X2

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,...,[CALCULATED]FederalYearsFiledCheckCategorical_Yellow-Age Consideration,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_2 or More Years,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Green,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Less than 2 Years,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_2 or More Years,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Green,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Less than 2 Years,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
47375,7,5,2778.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
3027,7,5,1933.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
30163,3,5,4824.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
20489,2,5,1303.0,0,1,0,0,1,1,0,...,0,0,1,0,0,1,0,1,0,0
46210,7,5,1830.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29374,2,6,4098.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
12881,4,5,4445.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
24885,7,6,2214.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
34699,5,5,3100.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
45128,1,5,3907.0,1,0,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0

In [1473]:
X3

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I485-130]SameEmployer_No,[I130]ImmigrationProceeding_No,[I130A]BeneficiaryInUS_No,...,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Green,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Less than 2 Years,[CALCULATED]LengthOfMarriageCategorical_Green,[CALCULATED]LengthOfMarriageCategorical_Red,[CALCULATED]LengthOfMarriageCategorical_Yellow,[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons
47375,7,5,2778.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
3027,7,5,1933.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
30163,3,5,4824.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
20489,2,5,1303.0,0,1,0,0,1,1,0,...,1,0,1,0,0,0,0,1,1,0
46210,7,5,1830.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29374,2,6,4098.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
12881,4,5,4445.0,0,1,0,1,1,1,1,...,1,0,1,0,0,0,0,1,1,0
24885,7,6,2214.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
34699,5,5,3100.0,0,1,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0
45128,1,5,3907.0,1,0,0,1,1,1,0,...,1,0,1,0,0,0,0,1,1,0

In [1474]:
y

47375    0
3027     0
30163    0
20489    1
46210    0
        ..
29374    0
12881    1
24885    0
34699    0
45128    1
Name: Target, Length: 75000, dtype: int64

In [1485]:
X_train, X_test, y_train, y_test = train_test_split(X3, y, test_size = 0.30)

In [1477]:
from sklearn.svm import SVC

In [1482]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)   # X2

SVC(kernel='linear')

In [1483]:
y_pred = svclassifier.predict(X_test)

In [1484]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[8623   76]
 [ 520 5781]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97      8699
           1       0.99      0.92      0.95      6301

    accuracy                           0.96     15000
   macro avg       0.97      0.95      0.96     15000
weighted avg       0.96      0.96      0.96     15000

In [1486]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)  #X3

SVC(kernel='linear')

In [1487]:
y_pred = svclassifier.predict(X_test)

In [1488]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[8621   28]
 [ 340 6011]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      8649
           1       1.00      0.95      0.97      6351

    accuracy                           0.98     15000
   macro avg       0.98      0.97      0.97     15000
weighted avg       0.98      0.98      0.98     15000

In [1499]:
xEncode2 = primeDfSubsetSVMSTFRandom[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN' ]].copy(True)

In [1500]:
xEncode2 = pd.get_dummies(xEncode2, columns= ['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN'])

In [1501]:
xEncode2.head(20)

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,...,[CALCULATED]LengthOfMarriageCategorical_Green,[CALCULATED]LengthOfMarriageCategorical_Red,[CALCULATED]LengthOfMarriageCategorical_Yellow,[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days,[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
24322,4,7,1162.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
48261,1,6,2194.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
39663,8,4,2790.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
994,7,5,4778.0,1,0,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
31505,9,4,1951.0,0,0,1,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
26284,7,6,1134.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
30774,18,4,4529.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
26191,5,10,4954.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
11336,15,5,4102.0,0,1,0,0,1,0,1,...,1,0,0,0,0,1,0,1,0,0
6110,4,6,1058.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
35836,7,5,3541.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
38483,3,5,4608.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
18246,1,6,1704.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
18917,24,0,1457.0,0,1,0,1,0,1,0,...,0,1,0,0,0,1,0,1,0,0
42762,8,5,2867.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
26268,17,2,5055.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
12424,14,4,2602.0,1,0,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
7579,4,4,2876.0,0,1,0,0,1,1,0,...,1,0,0,0,0,1,0,1,0,0
16680,0,4,3976.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0
34990,8,5,2837.0,0,1,0,1,0,1,0,...,1,0,0,0,0,1,0,1,0,0

In [1502]:
primeDfSubsetSVMSTFRandom

,[I130]StayingTogetherStatus,[I130]CurrentMaritalStatus,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[CALCULATED]AgeGapYears,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,[I485]CriminalityProvedConvictedTypeN,Target
24322,Same House,Married,No,No,Yes,No,4,Green,Green,7,1162.0,Age Gap < 9 Years,Eligible,Green,2 or More Years,Green,Green,Difference >= 731 Days,Green,0
48261,Same House,Married,No,No,Yes,No,1,Green,Green,6,2194.0,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0
39663,Same House,Married,No,No,Yes,No,8,Green,Green,4,2790.0,Age Gap < 9 Years,Eligible,Green,Less than 2 Years,Green,Green,Difference >= 731 Days,Green,1
994,Different States,Married,No,No,Yes,No,7,Green,Green,5,4778.0,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,1
31505,Same State - Different Address,Married,No,No,Yes,No,9,Green,Green,4,1951.0,Age Gap 9 - 15 Years,Eligible,Red,Green,Green,Green,Difference >= 731 Days,Green,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13719,Same State - Different Address,Married,No,No,Yes,No,27,Green,Green,1,2961.0,Age Gap >= 15 Years,Eligible,Green,Green,Less than 2 Years,Red,Difference >= 731 Days,Minor Reasons,1
3882,Same House,Married,No,No,No,No,13,Green,Green,2,3839.0,Age Gap 9 - 15 Years,Eligible,Green,Less than 2 Years,Green,Yellow,Difference >= 731 Days,Green,1
49498,Same House,Married,No,No,Yes,No,3,Green,Green,4,3103.0,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0
40710,Same State - Different Address,Married,No,No,Yes,No,7,Green,Green,5,4785.0,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,1
9820,Same House,Married,No,No,Yes,No,4,Green,Green,6,2641.0,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0

In [1503]:
X11 = xEncode2.drop(['[CALCULATED]AgeGapYears','[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate'], axis=1)

In [1504]:
X22 = xEncode2.drop(['[CALCULATED]AgeGapCategorical_Age Gap 9 - 15 Years','[CALCULATED]AgeGapCategorical_Age Gap < 9 Years','[CALCULATED]AgeGapCategorical_Age Gap >= 15 Years', '[CALCULATED]LengthOfMarriageCategorical_Green','[CALCULATED]LengthOfMarriageCategorical_Red','[CALCULATED]LengthOfMarriageCategorical_Yellow','[CALCULATED]LengthOfMarriageCategorical_Yellow-Age Consideration','[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference < 180 Days','[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference >= 731 Days','[CALCULATED]DiffEntryDateAndMarriageDateCategorical_Difference between 180 - 730 Days'], axis=1)

In [1505]:
y1 = primeDfSubsetSVMSTFRandom['Target']

In [1506]:
X_train, X_test, y_train, y_test = train_test_split(X11, y1, test_size = 0.20) # X11

In [1507]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)   # X11

SVC(kernel='linear')

In [1508]:
y_pred = svclassifier.predict(X_test)

In [1509]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[10011     0]
 [    0  4989]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     10011
           1       1.00      1.00      1.00      4989

    accuracy                           1.00     15000
   macro avg       1.00      1.00      1.00     15000
weighted avg       1.00      1.00      1.00     15000

In [1510]:
X_train, X_test, y_train, y_test = train_test_split(X22, y1, test_size = 0.20) # X11

In [1511]:
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)   # X11

SVC(kernel='linear')

In [1512]:
y_pred = svclassifier.predict(X_test)

In [1513]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[9905   86]
 [ 626 4383]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97      9991
           1       0.98      0.88      0.92      5009

    accuracy                           0.95     15000
   macro avg       0.96      0.93      0.95     15000
weighted avg       0.95      0.95      0.95     15000

In [1515]:
primeDF.dtypes

ApplicantID                                                               int64
[I130]PeopleNamePetitioner                                               object
[I130A]PeopleNameBeneficiary                                             object
[I130]DOBPetitioner                                                      object
[I130]MailingStateFilingPetitioner                                       object
[I130A]CountryOfBirthBeneficiary                                         object
[I130A]GenderBeneficiary                                                 object
[I130]PassportExpiryBeneficiary                                          object
[I130]PetitionerEthnicity                                                object
[I130]PetitionerRace                                                     object
[I130]PetitionerCitizenStatus                                            object
[I864]RegularIncome                                                       int64
[I864]SupplementalIncome                                                  int64
[I130]StayingTogetherStatus                                              object
[I130]CurrentMaritalStatus                                               object
[I864]FederalTaxFiled                                                    object
[I485-130]SameEmployer                                                   object
[I130]ImmigrationProceeding                                              object
[I485]CriminalityProvedConvicted                                         object
[I130]PreviousPetitionFiledPetitionerSameSpouse                          object
[I130]PreviousPetitionFiledDifferentSpouse                               object
[I130A]BeneficiaryInUS                                                   object
[I130-MarriageCertificate]SamePreparorNoterMinister                      object
[I130A]DOBBeneficiary                                                    object
[I130]GenderPetitioner                                                   object
[CALCULATED]AgeGapDays                                          timedelta64[ns]
[CALCULATED]AgePetitioner                                                 int64
[CALCULATED]AgeBeneficiary                                                int64
[CALCULATED]AgeGapYears                                                   int64
[I130]PreviousMaritalStatusPetitioner                                    object
[I130]PreviousMaritalStatusBeneficiary                                   object
[I130]PreviousLegallySeperatedCountryPetitioner                          object
[I130]NumberOfMarriagesPetitioner                                         int64
[I130]NumberOfMarriagesBeneficiary                                        int64
[I485]CriminalityProvedConvictedType                                     object
[I130]PreviousFiledPetitionerSameSpouseRejectionCondition                object
[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition             object
[I130A]BeneficiaryEthnicity                                              object
[I864]NumberOfDependents                                                  int64
[CALCULATED]FederalPovertyLineValue                                       int64
[CALCULATED]TotalIncome                                                   int64
[I130]DateOfMarriage                                                     object
[I130]I94DateofEntry                                                     object
[I130]LastMarriageEndDatePetitioner                                      object
[I130]LastMarriageEndDateBeneficiary                                     object
[I864]FederalTaxFiledYears                                               object
[CALCULATED]LengthOfMarriage                                              int64
[CALCULATED]YearsSinceDateofEntry                                         int64
[CALCULATED]TotalYearsFromLastMarriagePetitioner                        float64
[CALCULATED]TotalYearsFromLastMarriageBeneficiary                       float64
[CALCULATED]DiffEntryDateAndMarriageDate                                float64
[Calculated]FlagType                                                     object
[Calculated]FraudLikelihood                                              object
[Calculated]FraudDescriptive                                             object
[CALCULATED]AgeGapCategorical                                            object
[CALCULATED]IncomeCheckCategorical                                       object
[CALCULATED]FederalYearsFiledCheckCategorical                            object
[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical              object
[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical             object
[CALCULATED]LengthOfMarriageCategorical                                  object
[CALCULATED]DiffEntryDateAndMarriageDateCategorical                      object
Target                                                                    int64
[I485]CriminalityProvedConvictedTypeN                                    object
dtype: object

In [1516]:
def FlagTypeFn(x):
    if x == "Red":
        a=2
    elif x=="Yellow":
        a=1
    elif x=="Green":
        a=0
    
    return a

In [1517]:
primeDF['Target2'] =  primeDF['[Calculated]FlagType'].apply(lambda x: FlagTypeFn(x))

In [1518]:
primeDF[['Target2', '[Calculated]FlagType']]

       Target2 [Calculated]FlagType
22993        2                  Red
17799        2                  Red
47640        0                Green
7712         0                Green
9994         0                Green
...        ...                  ...
27211        1               Yellow
40667        0                Green
25383        2                  Red
49057        0                Green
15595        2                  Red

[750000 rows x 2 columns]

In [1519]:
primeDFSample10 = primeDF.sample(frac = 0.1)

In [1546]:
primeDFSample10Subset=primeDFSample10[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN','Target2' ]]

In [1521]:
primeDFSample10Subset['Target2'].value_counts()

0    43170
2    22439
1     9391
Name: Target2, dtype: int64

In [1526]:
xEncodeN = primeDFSample10Subset[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[I485]CriminalityProvedConvictedTypeN' ]].copy(True)

In [1527]:
xEncodeN = pd.get_dummies(xEncodeN, columns= ['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition','[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[I485]CriminalityProvedConvictedTypeN'])

In [1528]:
xEncodeN

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,...,[CALCULATED]FederalYearsFiledCheckCategorical_Yellow-Age Consideration,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_2 or More Years,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Green,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Less than 2 Years,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_2 or More Years,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Green,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Less than 2 Years,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
30149,3,6,1925.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
26239,1,2,4844.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
8548,7,6,2842.0,0,1,0,1,0,1,0,...,0,0,1,0,1,0,0,1,0,0
20787,2,5,2169.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
32214,28,1,5408.0,0,1,0,1,0,0,1,...,0,1,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1863,29,1,306.0,0,0,1,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
42566,3,5,3196.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
45607,3,4,3827.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
25615,7,6,1586.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
1959,3,3,1298.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0

In [1529]:
yN = primeDFSample10Subset['Target2']

In [1530]:
X_train, X_test, y_train, y_test = train_test_split(xEncodeN, yN, train_size=0.8, random_state = 0)

In [1532]:
linear = svm.SVC(kernel='linear', C=1, decision_function_shape='ovr').fit(X_train, y_train)

In [1533]:
linear_pred = linear.predict(X_test)

In [1535]:
accuracy_lin = linear.score(X_test, y_test)
#print(“Accuracy Linear Kernel:”, accuracy_lin)

In [1536]:
accuracy_lin

0.9439333333333333

In [1537]:
cm_lin = confusion_matrix(y_test, linear_pred)

In [1538]:
cm_lin

array([[8616,   53,    1],
       [ 370, 1397,   42],
       [ 327,   48, 4146]], dtype=int64)

In [1539]:
linear2 = svm.SVC(kernel='linear', C=1, decision_function_shape='ovo').fit(X_train, y_train)

In [1540]:
linear_pred2 = linear2.predict(X_test)

In [1541]:
accuracy_lin2 = linear2.score(X_test, y_test)

In [1542]:
accuracy_lin2

0.9439333333333333

In [1543]:
cm_lin2 = confusion_matrix(y_test, linear_pred2)

In [1544]:
cm_lin2

array([[8616,   53,    1],
       [ 370, 1397,   42],
       [ 327,   48, 4146]], dtype=int64)

In [1547]:
primeDFSample10Subset.to_csv('primeDFSample10Subset.csv',index=False)

In [1548]:
primeDfSubsetSVMSTFRandom.to_csv('primeDfSubsetSVMSTFRandom.csv',index=False)

In [1549]:
primeDF

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,Target,[I485]CriminalityProvedConvictedTypeN,Target2
22993,1322993,Jennifer Torres,Lori Herrera,1961-11-11,North Carolina,South Sudan,F,2023-04-01,Not Hispanic or Latino,American Indian or Alaska Native,...,Age Gap >= 15 Years,Eligible,Red,Green,Less than 2 Years,Green,Difference >= 731 Days,1,Green,2
17799,1117799,Daniel Lopez,Thomas Bowers,1990-07-06,Mississippi,South Africa,F,2029-05-14,Not Hispanic or Latino,Asian,...,Age Gap >= 15 Years,Eligible,Green,Less than 2 Years,Green,Red,Difference >= 731 Days,1,Minor Reasons,2
47640,2847640,Laurie Copeland,Andrew Lopez,1967-12-08,South Dakota,Paraguay,M,2031-10-11,Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
7712,2407712,Sarah Moore,Thomas Morrison,1995-09-02,New Jersey,Japan,F,2027-04-15,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
9994,2109994,Lisa Reyes,Jordan Rodriguez,1974-07-23,Pennsylvania,Russian Federation,F,2024-01-19,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27211,2727211,Tanya Munoz,Laurie Reid,1970-12-10,Arizona,Ukraine,F,2026-09-16,Hispanic or Latino,Black or African Ammerican,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,1,Green,1
40667,2240667,Jessica Foster,Vanessa Thompson,1979-07-27,Wyoming,St Kitts & Nevis,F,2025-09-02,Not Hispanic or Latino,Black or African Ammerican,...,Age Gap < 9 Years,Eligible,Green,2 or More Years,Green,Green,Difference >= 731 Days,0,Green,0
25383,1025383,Heather Wilcox,Patrick Garcia,1988-09-03,New York,Mexico,M,2025-07-15,Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Less than 2 Years,Red,Difference >= 731 Days,1,Green,2
49057,2649057,Chad Smith,Stacy George,1997-11-09,Maryland,Indonesia,F,2030-05-28,Not Hispanic or Latino,Asian,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
15595,1115595,Matthew Parsons,Kelly Morgan,1975-02-21,Montana,Costa Rica,M,2028-05-13,Not Hispanic or Latino,White,...,Age Gap 9 - 15 Years,Eligible,Red,Less than 2 Years,Green,Green,Difference >= 731 Days,1,Green,2

In [1554]:
primeDFRemDup1 = primeDF[primeDF.duplicated(subset=['[I130]StayingTogetherStatus','[I130]CurrentMaritalStatus','[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN'], keep=False)]
print (primeDFRemDup1)

       ApplicantID [I130]PeopleNamePetitioner [I130A]PeopleNameBeneficiary  \
47640      2847640            Laurie Copeland                 Andrew Lopez
7712       2407712                Sarah Moore              Thomas Morrison
9994       2109994                 Lisa Reyes             Jordan Rodriguez
23797      2523797           Mrs. Karen Brown                  Stacey Bell
32765      2732765         Jennifer Rodriguez              Victoria Nelson
...            ...                        ...                          ...
19812      2919812               Nicole White             Christopher Berg
44194      2244194            Rebecca Jackson               Lance Mitchell
49405      2449405            Dustin Robinson                  Stacy White
20610      2220610                Jason Smith               Michelle Munoz
49057      2649057                 Chad Smith                 Stacy George

      [I130]DOBPetitioner [I130]MailingStateFilingPetitioner  \
47640          1967-12-08                       South Dakota
7712           1995-09-02                         New Jersey
9994           1974-07-23                       Pennsylvania
23797          1972-03-17                     North Carolina
32765          1974-08-09                            Vermont
...                   ...                                ...
19812          1998-04-19                             Hawaii
44194          1973-08-30                          Louisiana
49405          1970-10-06                           Michigan
20610          1989-04-08                           Delaware
49057          1997-11-09                           Maryland

      [I130A]CountryOfBirthBeneficiary [I130A]GenderBeneficiary  \
47640                         Paraguay                        M
7712                             Japan                        F
9994                Russian Federation                        F
23797                         Malaysia                        M
32765                        Macedonia                        M
...                                ...                      ...
19812                             Oman                        F
44194                           Serbia                        M
49405                       East Timor                        F
20610                         Honduras                        M
49057                        Indonesia                        F

      [I130]PassportExpiryBeneficiary [I130]PetitionerEthnicity  \
47640                      2031-10-11        Hispanic or Latino
7712                       2027-04-15    Not Hispanic or Latino
9994                       2024-01-19    Not Hispanic or Latino
23797                      2024-11-17    Not Hispanic or Latino
32765                      2028-05-08    Not Hispanic or Latino
...                               ...                       ...
19812                      2028-11-04        Hispanic or Latino
44194                      2025-05-27    Not Hispanic or Latino
49405                      2027-01-24             Not Specified
20610                      2027-04-03    Not Hispanic or Latino
49057                      2030-05-28    Not Hispanic or Latino

                            [I130]PetitionerRace  ...  \
47640           American Indian or Alaska Native  ...
7712                                       White  ...
9994   Native Hawaiian or Other Pacific Islander  ...
23797                                      White  ...
32765                                      White  ...
...                                          ...  ...
19812           American Indian or Alaska Native  ...
44194           American Indian or Alaska Native  ...
49405                                      White  ...
20610                 Black or African Ammerican  ...
49057                                      Asian  ...

      [CALCULATED]AgeGapCategorical  [CALCULATED]IncomeCheckCategorical  \
47640             Age Gap < 9 Years                            Eligible
7712              Age Gap < 9 Years                            Eligible
9994              Age Gap < 9 Years                            Eligible
23797             Age Gap < 9 Years                            Eligible
32765             Age Gap < 9 Years                            Eligible
...                             ...                                 ...
19812             Age Gap < 9 Years                            Eligible
44194             Age Gap < 9 Years                            Eligible
49405             Age Gap < 9 Years                            Eligible
20610             Age Gap < 9 Years                            Eligible
49057             Age Gap < 9 Years                            Eligible

       [CALCULATED]FederalYearsFiledCheckCategorical  \
47640                                          Green
7712                                           Green
9994                                           Green
23797                                          Green
32765                                          Green
...                                              ...
19812                                          Green
44194                                          Green
49405                                          Green
20610                                          Green
49057                                          Green

      [CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical  \
47640                                              Green
7712                                               Green
9994                                               Green
23797                                              Green
32765                                              Green
...                                                  ...
19812                                              Green
44194                                              Green
49405                                              Green
20610                                              Green
49057                                              Green

      [CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical  \
47640                                              Green
7712                                               Green
9994                                               Green
23797                                              Green
32765                                              Green
...                                                  ...
19812                                              Green
44194                                              Green
49405                                              Green
20610                                              Green
49057                                              Green

      [CALCULATED]LengthOfMarriageCategorical  \
47640                                   Green
7712                                    Green
9994                                    Green
23797                                   Green
32765                                   Green
...                                       ...
19812                                   Green
44194                                   Green
49405                                   Green
20610                                   Green
49057                                   Green

      [CALCULATED]DiffEntryDateAndMarriageDateCategorical Target  \
47640                             Difference >= 731 Days       0
7712                              Difference >= 731 Days       0
9994                              Difference >= 731 Days       0
23797                             Difference >= 731 Days       0
32765                             Difference >= 731 Days       0
...                                                  ...     ...
19812                             Difference >= 731 Days       0
44194                             Difference >= 731 Days       0
49405                             Difference >= 731 Days       0
20610                             Difference >= 731 Days       0
49057                             Difference >= 731 Days       0

      [I485]CriminalityProvedConvictedTypeN Target2
47640                                 Green       0
7712                                  Green       0
9994                                  Green       0
23797                                 Green       0
32765                                 Green       0
...                                     ...     ...
19812                                 Green       0
44194                                 Green       0
49405                                 Green       0
20610                                 Green       0
49057                                 Green       0

[335703 rows x 64 columns]

In [1555]:
primeDFRemDup1

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,Target,[I485]CriminalityProvedConvictedTypeN,Target2
47640,2847640,Laurie Copeland,Andrew Lopez,1967-12-08,South Dakota,Paraguay,M,2031-10-11,Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
7712,2407712,Sarah Moore,Thomas Morrison,1995-09-02,New Jersey,Japan,F,2027-04-15,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
9994,2109994,Lisa Reyes,Jordan Rodriguez,1974-07-23,Pennsylvania,Russian Federation,F,2024-01-19,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
23797,2523797,Mrs. Karen Brown,Stacey Bell,1972-03-17,North Carolina,Malaysia,M,2024-11-17,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
32765,2732765,Jennifer Rodriguez,Victoria Nelson,1974-08-09,Vermont,Macedonia,M,2028-05-08,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19812,2919812,Nicole White,Christopher Berg,1998-04-19,Hawaii,Oman,F,2028-11-04,Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
44194,2244194,Rebecca Jackson,Lance Mitchell,1973-08-30,Louisiana,Serbia,M,2025-05-27,Not Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
49405,2449405,Dustin Robinson,Stacy White,1970-10-06,Michigan,East Timor,F,2027-01-24,Not Specified,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
20610,2220610,Jason Smith,Michelle Munoz,1989-04-08,Delaware,Honduras,M,2027-04-03,Not Hispanic or Latino,Black or African Ammerican,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
49057,2649057,Chad Smith,Stacy George,1997-11-09,Maryland,Indonesia,F,2030-05-28,Not Hispanic or Latino,Asian,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0

In [1557]:
primeDFRemDup1['Target'].value_counts()

0    325279
1     10424
Name: Target, dtype: int64

In [1558]:
primeDFRemDup1['Target2'].value_counts()

0    325279
1      8920
2      1504
Name: Target2, dtype: int64

In [1559]:
primeDFRemDup2 = primeDF[primeDF.duplicated(subset=['[I130]StayingTogetherStatus','[I130]CurrentMaritalStatus','[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[I485]CriminalityProvedConvictedTypeN'], keep=False)]
print (primeDFRemDup2)

       ApplicantID [I130]PeopleNamePetitioner [I130A]PeopleNameBeneficiary  \
47640      2847640            Laurie Copeland                 Andrew Lopez
7712       2407712                Sarah Moore              Thomas Morrison
9994       2109994                 Lisa Reyes             Jordan Rodriguez
23797      2523797           Mrs. Karen Brown                  Stacey Bell
32765      2732765         Jennifer Rodriguez              Victoria Nelson
...            ...                        ...                          ...
19812      2919812               Nicole White             Christopher Berg
44194      2244194            Rebecca Jackson               Lance Mitchell
49405      2449405            Dustin Robinson                  Stacy White
20610      2220610                Jason Smith               Michelle Munoz
49057      2649057                 Chad Smith                 Stacy George

      [I130]DOBPetitioner [I130]MailingStateFilingPetitioner  \
47640          1967-12-08                       South Dakota
7712           1995-09-02                         New Jersey
9994           1974-07-23                       Pennsylvania
23797          1972-03-17                     North Carolina
32765          1974-08-09                            Vermont
...                   ...                                ...
19812          1998-04-19                             Hawaii
44194          1973-08-30                          Louisiana
49405          1970-10-06                           Michigan
20610          1989-04-08                           Delaware
49057          1997-11-09                           Maryland

      [I130A]CountryOfBirthBeneficiary [I130A]GenderBeneficiary  \
47640                         Paraguay                        M
7712                             Japan                        F
9994                Russian Federation                        F
23797                         Malaysia                        M
32765                        Macedonia                        M
...                                ...                      ...
19812                             Oman                        F
44194                           Serbia                        M
49405                       East Timor                        F
20610                         Honduras                        M
49057                        Indonesia                        F

      [I130]PassportExpiryBeneficiary [I130]PetitionerEthnicity  \
47640                      2031-10-11        Hispanic or Latino
7712                       2027-04-15    Not Hispanic or Latino
9994                       2024-01-19    Not Hispanic or Latino
23797                      2024-11-17    Not Hispanic or Latino
32765                      2028-05-08    Not Hispanic or Latino
...                               ...                       ...
19812                      2028-11-04        Hispanic or Latino
44194                      2025-05-27    Not Hispanic or Latino
49405                      2027-01-24             Not Specified
20610                      2027-04-03    Not Hispanic or Latino
49057                      2030-05-28    Not Hispanic or Latino

                            [I130]PetitionerRace  ...  \
47640           American Indian or Alaska Native  ...
7712                                       White  ...
9994   Native Hawaiian or Other Pacific Islander  ...
23797                                      White  ...
32765                                      White  ...
...                                          ...  ...
19812           American Indian or Alaska Native  ...
44194           American Indian or Alaska Native  ...
49405                                      White  ...
20610                 Black or African Ammerican  ...
49057                                      Asian  ...

      [CALCULATED]AgeGapCategorical  [CALCULATED]IncomeCheckCategorical  \
47640             Age Gap < 9 Years                            Eligible
7712              Age Gap < 9 Years                            Eligible
9994              Age Gap < 9 Years                            Eligible
23797             Age Gap < 9 Years                            Eligible
32765             Age Gap < 9 Years                            Eligible
...                             ...                                 ...
19812             Age Gap < 9 Years                            Eligible
44194             Age Gap < 9 Years                            Eligible
49405             Age Gap < 9 Years                            Eligible
20610             Age Gap < 9 Years                            Eligible
49057             Age Gap < 9 Years                            Eligible

       [CALCULATED]FederalYearsFiledCheckCategorical  \
47640                                          Green
7712                                           Green
9994                                           Green
23797                                          Green
32765                                          Green
...                                              ...
19812                                          Green
44194                                          Green
49405                                          Green
20610                                          Green
49057                                          Green

      [CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical  \
47640                                              Green
7712                                               Green
9994                                               Green
23797                                              Green
32765                                              Green
...                                                  ...
19812                                              Green
44194                                              Green
49405                                              Green
20610                                              Green
49057                                              Green

      [CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical  \
47640                                              Green
7712                                               Green
9994                                               Green
23797                                              Green
32765                                              Green
...                                                  ...
19812                                              Green
44194                                              Green
49405                                              Green
20610                                              Green
49057                                              Green

      [CALCULATED]LengthOfMarriageCategorical  \
47640                                   Green
7712                                    Green
9994                                    Green
23797                                   Green
32765                                   Green
...                                       ...
19812                                   Green
44194                                   Green
49405                                   Green
20610                                   Green
49057                                   Green

      [CALCULATED]DiffEntryDateAndMarriageDateCategorical Target  \
47640                             Difference >= 731 Days       0
7712                              Difference >= 731 Days       0
9994                              Difference >= 731 Days       0
23797                             Difference >= 731 Days       0
32765                             Difference >= 731 Days       0
...                                                  ...     ...
19812                             Difference >= 731 Days       0
44194                             Difference >= 731 Days       0
49405                             Difference >= 731 Days       0
20610                             Difference >= 731 Days       0
49057                             Difference >= 731 Days       0

      [I485]CriminalityProvedConvictedTypeN Target2
47640                                 Green       0
7712                                  Green       0
9994                                  Green       0
23797                                 Green       0
32765                                 Green       0
...                                     ...     ...
19812                                 Green       0
44194                                 Green       0
49405                                 Green       0
20610                                 Green       0
49057                                 Green       0

[336554 rows x 64 columns]

In [1560]:
primeDFRemDup2

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,Target,[I485]CriminalityProvedConvictedTypeN,Target2
47640,2847640,Laurie Copeland,Andrew Lopez,1967-12-08,South Dakota,Paraguay,M,2031-10-11,Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
7712,2407712,Sarah Moore,Thomas Morrison,1995-09-02,New Jersey,Japan,F,2027-04-15,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
9994,2109994,Lisa Reyes,Jordan Rodriguez,1974-07-23,Pennsylvania,Russian Federation,F,2024-01-19,Not Hispanic or Latino,Native Hawaiian or Other Pacific Islander,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
23797,2523797,Mrs. Karen Brown,Stacey Bell,1972-03-17,North Carolina,Malaysia,M,2024-11-17,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
32765,2732765,Jennifer Rodriguez,Victoria Nelson,1974-08-09,Vermont,Macedonia,M,2028-05-08,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19812,2919812,Nicole White,Christopher Berg,1998-04-19,Hawaii,Oman,F,2028-11-04,Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
44194,2244194,Rebecca Jackson,Lance Mitchell,1973-08-30,Louisiana,Serbia,M,2025-05-27,Not Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
49405,2449405,Dustin Robinson,Stacy White,1970-10-06,Michigan,East Timor,F,2027-01-24,Not Specified,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
20610,2220610,Jason Smith,Michelle Munoz,1989-04-08,Delaware,Honduras,M,2027-04-03,Not Hispanic or Latino,Black or African Ammerican,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
49057,2649057,Chad Smith,Stacy George,1997-11-09,Maryland,Indonesia,F,2030-05-28,Not Hispanic or Latino,Asian,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0

In [1561]:
primeDFRemDup2['Target'].value_counts()

0    325647
1     10907
Name: Target, dtype: int64

In [1562]:
primeDFRemDup2['Target2'].value_counts()

0    325647
1      9362
2      1545
Name: Target2, dtype: int64

In [1563]:
primeDFRemDup1.to_csv('primeDFRemDup1.csv',index=False)

In [1564]:
primeDFRemDup2.to_csv('primeDFRemDup2.csv',index=False)

In [1570]:
primeDFRemDup1_0 = primeDFRemDup1[primeDFRemDup1['Target'] < 1].sample(n = 89576)

In [1571]:
primeDFRemDup1_12 = primeDFRemDup1[primeDFRemDup1['Target'] > 0]

In [1572]:
primeDFRemDup1_012 = [primeDFRemDup1_0, primeDFRemDup1_12]

In [1573]:
primeDFRemDupSample = pd.concat(primeDFRemDup1_012)

In [1574]:
primeDFRemDupSample['Target'].value_counts()

0    89576
1    10424
Name: Target, dtype: int64

In [1576]:
primeDFRemDup2_0 = primeDFRemDup2[primeDFRemDup2['Target'] < 1].sample(n = 89093)

In [1577]:
primeDFRemDup2_12 = primeDFRemDup2[primeDFRemDup2['Target'] > 0]

In [1578]:
primeDFRemDup2_012 = [primeDFRemDup2_0, primeDFRemDup2_12]

In [1579]:
primeDFRemDup2Sample = pd.concat(primeDFRemDup2_012)

In [1580]:
primeDFRemDup2Sample['Target'].value_counts()

0    89093
1    10907
Name: Target, dtype: int64

In [1581]:
primeDFRemDupSample.to_csv('primeDFRemDupSample.csv',index=False)

In [1582]:
primeDFRemDup2Sample.to_csv('primeDFRemDup2Sample.csv',index=False)

In [1583]:
primeDFRemDupSample1Subset=primeDFRemDupSample[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical','Target', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN','Target2' ]]

In [1584]:
primeDFRemDupSample2Subset=primeDFRemDupSample[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical','Target', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN','Target2' ]]

In [1597]:
primeDFRemDupSample1Subset.to_csv('primeDFRemDupSample1Subset.csv',index=False)

In [1599]:
primeDFRemDupSample2Subset.to_csv('primeDFRemDupSample2Subset.csv',index=False)

In [1593]:
primeDFRemDupSample1Subset = primeDFRemDupSample1Subset.sample(frac=1)

In [1595]:
primeDFRemDupSample2Subset = primeDFRemDupSample2Subset.sample(frac=1)

In [1587]:
primeDFRemDupSample1Subset

,[I130]StayingTogetherStatus,[I130]CurrentMaritalStatus,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[CALCULATED]AgeGapYears,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[CALCULATED]LengthOfMarriage,...,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,Target,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,[I485]CriminalityProvedConvictedTypeN,Target2
44450,Same House,Married,No,No,Yes,No,4,Green,Green,6,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
27516,Same House,Married,No,No,Yes,No,0,Green,Green,4,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
7345,Same House,Married,No,No,Yes,No,7,Green,Green,8,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
43595,Same House,Married,No,No,Yes,No,1,Green,Green,5,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
18824,Same House,Married,No,No,Yes,No,7,Green,Green,6,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18810,Same House,Married,No,No,No,No,4,Green,Green,5,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,1,Difference >= 731 Days,Green,1
26012,Same House,Married,No,No,Yes,No,2,Green,Green,2,...,Age Gap < 9 Years,Eligible,Yellow,Green,Green,Green,1,Difference >= 731 Days,Green,1
47711,Same House,Married,No,No,Yes,No,7,Green,Green,4,...,Age Gap < 9 Years,Eligible,Yellow,Green,Green,Green,1,Difference >= 731 Days,Green,1
42252,Same House,Married,No,No,Yes,No,0,Green,Green,1,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Yellow-Age Consideration,1,Difference >= 731 Days,Green,1
24328,Same House,Married,No,No,Yes,No,0,Green,Green,1,...,Age Gap < 9 Years,Eligible,Yellow,Green,Green,Yellow-Age Consideration,1,Difference >= 731 Days,Green,1

In [1591]:
primeDFRemDupSample2Subset

,[I130]StayingTogetherStatus,[I130]CurrentMaritalStatus,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[CALCULATED]AgeGapYears,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[CALCULATED]LengthOfMarriage,...,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,Target,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,[I485]CriminalityProvedConvictedTypeN,Target2
44450,Same House,Married,No,No,Yes,No,4,Green,Green,6,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
27516,Same House,Married,No,No,Yes,No,0,Green,Green,4,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
7345,Same House,Married,No,No,Yes,No,7,Green,Green,8,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
43595,Same House,Married,No,No,Yes,No,1,Green,Green,5,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
18824,Same House,Married,No,No,Yes,No,7,Green,Green,6,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,0,Difference >= 731 Days,Green,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18810,Same House,Married,No,No,No,No,4,Green,Green,5,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,1,Difference >= 731 Days,Green,1
26012,Same House,Married,No,No,Yes,No,2,Green,Green,2,...,Age Gap < 9 Years,Eligible,Yellow,Green,Green,Green,1,Difference >= 731 Days,Green,1
47711,Same House,Married,No,No,Yes,No,7,Green,Green,4,...,Age Gap < 9 Years,Eligible,Yellow,Green,Green,Green,1,Difference >= 731 Days,Green,1
42252,Same House,Married,No,No,Yes,No,0,Green,Green,1,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Yellow-Age Consideration,1,Difference >= 731 Days,Green,1
24328,Same House,Married,No,No,Yes,No,0,Green,Green,1,...,Age Gap < 9 Years,Eligible,Yellow,Green,Green,Yellow-Age Consideration,1,Difference >= 731 Days,Green,1

In [1625]:
primeDFRemDup3.to_csv('primeDFRemDup3.csv',index=False)

In [1629]:
primeDFRemDup3['[I485]CriminalityProvedConvictedTypeN'].unique()

array(['Green', 'Minor Reasons', 'Major Reasons'], dtype=object)

In [ ]:
  '[I130-MarriageCertificate]SamePreparorNoterMinister', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical','Target', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN','Target2' ]]

In [1622]:
primeDFRemDup3 = primeDF.drop_duplicates(['[I130]StayingTogetherStatus','[I130]CurrentMaritalStatus','[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[I485]CriminalityProvedConvictedTypeN'],keep= 'last')
primeDFRemDup3

,ApplicantID,[I130]PeopleNamePetitioner,[I130A]PeopleNameBeneficiary,[I130]DOBPetitioner,[I130]MailingStateFilingPetitioner,[I130A]CountryOfBirthBeneficiary,[I130A]GenderBeneficiary,[I130]PassportExpiryBeneficiary,[I130]PetitionerEthnicity,[I130]PetitionerRace,...,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,Target,[I485]CriminalityProvedConvictedTypeN,Target2
22993,1322993,Jennifer Torres,Lori Herrera,1961-11-11,North Carolina,South Sudan,F,2023-04-01,Not Hispanic or Latino,American Indian or Alaska Native,...,Age Gap >= 15 Years,Eligible,Red,Green,Less than 2 Years,Green,Difference >= 731 Days,1,Green,2
17799,1117799,Daniel Lopez,Thomas Bowers,1990-07-06,Mississippi,South Africa,F,2029-05-14,Not Hispanic or Latino,Asian,...,Age Gap >= 15 Years,Eligible,Green,Less than 2 Years,Green,Red,Difference >= 731 Days,1,Minor Reasons,2
41693,2241693,Gail Daniels,Paul Cross,1989-11-05,New Jersey,China,M,2029-02-21,Not Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Red,Green,Green,Green,Difference >= 731 Days,1,Green,2
1145,1101145,Charles Henry,Richard Parker,1967-07-07,Nevada,Uruguay,M,2031-06-13,Not Hispanic or Latino,Black or African Ammerican,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Red,Difference >= 731 Days,1,Minor Reasons,2
14672,2814672,Charles Hall Jr.,John Perez,1976-05-04,Illinois,Trinidad & Tobago,M,2024-03-15,Not Hispanic or Latino,White,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27211,2727211,Tanya Munoz,Laurie Reid,1970-12-10,Arizona,Ukraine,F,2026-09-16,Hispanic or Latino,Black or African Ammerican,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,1,Green,1
40667,2240667,Jessica Foster,Vanessa Thompson,1979-07-27,Wyoming,St Kitts & Nevis,F,2025-09-02,Not Hispanic or Latino,Black or African Ammerican,...,Age Gap < 9 Years,Eligible,Green,2 or More Years,Green,Green,Difference >= 731 Days,0,Green,0
25383,1025383,Heather Wilcox,Patrick Garcia,1988-09-03,New York,Mexico,M,2025-07-15,Hispanic or Latino,American Indian or Alaska Native,...,Age Gap < 9 Years,Eligible,Green,Green,Less than 2 Years,Red,Difference >= 731 Days,1,Green,2
49057,2649057,Chad Smith,Stacy George,1997-11-09,Maryland,Indonesia,F,2030-05-28,Not Hispanic or Latino,Asian,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,0,Green,0
15595,1115595,Matthew Parsons,Kelly Morgan,1975-02-21,Montana,Costa Rica,M,2028-05-13,Not Hispanic or Latino,White,...,Age Gap 9 - 15 Years,Eligible,Red,Less than 2 Years,Green,Green,Difference >= 731 Days,1,Green,2

In [ ]:
primeDFRemDup3ColRem

In [1626]:
 primeDFRemDup3ColRem = primeDFRemDup3[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]AgeGapCategorical', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[CALCULATED]LengthOfMarriageCategorical', '[CALCULATED]DiffEntryDateAndMarriageDateCategorical', '[I485]CriminalityProvedConvictedTypeN','Target','Target2' ]].copy(True)

In [1628]:
primeDFRemDup3ColRem.to_csv('primeDFRemDup3ColRem.csv',index=False)

In [1630]:
primeDFRemDup3ColRem['Target2'].value_counts()

2    221856
0    213741
1     87938
Name: Target2, dtype: int64

In [1631]:
primeDFRemDup3ColRem_0 = primeDFRemDup3ColRem[primeDFRemDup3ColRem['Target2'] < 1].sample(n = 85000)

In [1633]:
primeDFRemDup3ColRem_1 = primeDFRemDup3ColRem[primeDFRemDup3ColRem['Target2'] == 1].sample(n = 10000)

In [1634]:
primeDFRemDup3ColRem_2 = primeDFRemDup3ColRem[primeDFRemDup3ColRem['Target2'] > 1].sample(n = 5000)

In [1635]:
primeDFRemDup3ColRem_012 = [primeDFRemDup3ColRem_0, primeDFRemDup3ColRem_1, primeDFRemDup3ColRem_2]

In [1636]:
primeDFRemDup3ColRemSample = pd.concat(primeDFRemDup3ColRem_012)

In [1637]:
primeDFRemDup3ColRemSample['Target2'].value_counts()

0    85000
1    10000
2     5000
Name: Target2, dtype: int64

In [1647]:
primeDFRemDup3ColRemSample.sample(frac = 1)

,[I130]StayingTogetherStatus,[I130]CurrentMaritalStatus,[I485-130]SameEmployer,[I130]ImmigrationProceeding,[I130A]BeneficiaryInUS,[I130-MarriageCertificate]SamePreparorNoterMinister,[CALCULATED]AgeGapYears,[I130]PreviousFiledPetitionerSameSpouseRejectionCondition,[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition,[CALCULATED]LengthOfMarriage,...,[CALCULATED]AgeGapCategorical,[CALCULATED]IncomeCheckCategorical,[CALCULATED]FederalYearsFiledCheckCategorical,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical,[CALCULATED]LengthOfMarriageCategorical,[CALCULATED]DiffEntryDateAndMarriageDateCategorical,[I485]CriminalityProvedConvictedTypeN,Target,Target2
44744,Same House,Married,No,No,Yes,No,3,Green,Green,4,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0
23713,Same House,Married,No,No,Yes,No,0,Green,Green,4,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0
9813,Same House,Married,No,No,No,No,7,Green,Green,4,...,Age Gap < 9 Years,Eligible,Green,2 or More Years,Green,Green,Difference >= 731 Days,Green,1,1
24666,Same House,Married,No,No,Yes,No,0,Green,Green,9,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0
45786,Same House,Married,No,No,Yes,No,2,Green,Green,8,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41804,Same House,Married,No,No,Yes,No,1,Green,Green,9,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0
46725,Same House,Married,No,No,Yes,No,2,Green,Green,6,...,Age Gap < 9 Years,Eligible,Green,2 or More Years,Green,Green,Difference >= 731 Days,Green,0,0
41058,Same House,Married,No,No,Yes,No,1,Green,Green,4,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0
587,Same House,Married,No,No,Yes,No,7,Green,Green,3,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0
49956,Same House,Married,No,No,Yes,No,0,Green,Green,7,...,Age Gap < 9 Years,Eligible,Green,Green,Green,Green,Difference >= 731 Days,Green,0,0

In [1648]:
xEncodeNeww = primeDFRemDup3ColRemSample[['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[CALCULATED]AgeGapYears', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition', '[CALCULATED]LengthOfMarriage', '[CALCULATED]DiffEntryDateAndMarriageDate', '[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[I485]CriminalityProvedConvictedTypeN' ]].copy(True)

In [1649]:
xEncodeNeww = pd.get_dummies(xEncodeNeww, columns= ['[I130]StayingTogetherStatus', '[I130]CurrentMaritalStatus', '[I485-130]SameEmployer', '[I130]ImmigrationProceeding', '[I130A]BeneficiaryInUS', '[I130-MarriageCertificate]SamePreparorNoterMinister', '[I130]PreviousFiledPetitionerSameSpouseRejectionCondition', '[I130]PreviousPetitionFiledDifferentSpouseRejectionCondition','[CALCULATED]IncomeCheckCategorical', '[CALCULATED]FederalYearsFiledCheckCategorical', '[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical', '[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical', '[I485]CriminalityProvedConvictedTypeN'])

In [1650]:
xEncodeNeww

,[CALCULATED]AgeGapYears,[CALCULATED]LengthOfMarriage,[CALCULATED]DiffEntryDateAndMarriageDate,[I130]StayingTogetherStatus_Different States,[I130]StayingTogetherStatus_Same House,[I130]StayingTogetherStatus_Same State - Different Address,[I130]CurrentMaritalStatus_Married,[I130]CurrentMaritalStatus_Separated,[I485-130]SameEmployer_No,[I485-130]SameEmployer_Yes,...,[CALCULATED]FederalYearsFiledCheckCategorical_Yellow-Age Consideration,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_2 or More Years,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Green,[CALCULATED]TotalYearsFromLastMarriagePetitionerCategorical_Less than 2 Years,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_2 or More Years,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Green,[CALCULATED]TotalYearsFromLastMarriageBeneficiaryCategorical_Less than 2 Years,[I485]CriminalityProvedConvictedTypeN_Green,[I485]CriminalityProvedConvictedTypeN_Major Reasons,[I485]CriminalityProvedConvictedTypeN_Minor Reasons
21819,0,6,814.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
41430,7,5,3119.0,0,1,0,1,0,1,0,...,0,0,1,0,1,0,0,1,0,0
15237,3,5,2009.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
42233,6,3,2458.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
23764,7,6,4270.0,0,1,0,1,0,1,0,...,0,0,1,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37493,8,6,4644.0,0,1,0,0,1,1,0,...,0,0,1,0,0,1,0,1,0,0
44371,5,3,223.0,0,1,0,1,0,0,1,...,0,0,0,1,0,1,0,1,0,0
22816,11,4,3478.0,0,0,1,1,0,0,1,...,0,1,0,0,0,1,0,1,0,0
9589,14,5,3772.0,0,0,1,1,0,0,1,...,0,0,1,0,0,1,0,0,0,1
48869,5,5,3688.0,0,1,0,1,0,1,0,...,0,0,0,1,0,1,0,1,0,0

In [1651]:
yNeww = primeDFRemDup3ColRemSample['Target2']

In [1652]:
X_trainN, X_testN, y_trainN, y_testN = train_test_split(xEncodeNeww, yNeww, train_size=0.8, random_state = 0)

In [1653]:
linearNew = svm.SVC(kernel='linear', C=1, decision_function_shape='ovr').fit(X_trainN, y_trainN)

In [1654]:
linear_predNew = linearNew.predict(X_testN)

In [1655]:
accuracy_linNew = linearNew.score(X_testN, y_testN)

In [1656]:
accuracy_linNew

0.94965

In [1657]:
cm_linNew = confusion_matrix(y_testN, linear_predNew)

In [1658]:
cm_linNew

array([[16904,    83,     0],
       [  676,  1302,    19],
       [  193,    36,   787]], dtype=int64)

In [ ]:
linearNew2 = svm.SVC(kernel='linear', C=1, decision_function_shape='ovo').fit(X_train, y_train)

In [ ]:
linear_predNew2 = linearNew2.predict(X_testN)

In [ ]:
accuracy_linNew2 = linearNew2.score(X_testN, y_testN)

In [ ]:
cm_linNew = confusion_matrix(y_testN, linear_predNew2)